IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::MessageFlowCoordinator Class Reference
IEEE::_1588::PTP::_2019::MessageFlowCoordinator Class Reference
Message Flow Integration Coordinator.
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/message_flow_integration.hpp>
Public Member Functions
MessageFlowCoordinator (Integration::BMCAIntegration &bmca, SyncIntegration &sync, servo::ServoIntegration &servo, Clocks::PtpPort &port) noexcept
Construct message flow coordinator.
Types::PTPError configure (const MessageFlowConfiguration &config) noexcept
Configure message flow coordinator.
Types::PTPError start () noexcept
Start message flow processing.
void stop () noexcept
Stop message flow processing.
Types::PTPError process_announce_message (const AnnounceMessage &message, std::uint64_t reception_timestamp_ns) noexcept
Process received Announce message.
Types::PTPError process_sync_message (const SyncMessage &message, std::uint64_t reception_timestamp_ns) noexcept
Process received Sync message.
Types::PTPError process_follow_up_message (const FollowUpMessage &message) noexcept
Process received Follow_Up message.
Types::PTPError process_delay_resp_message (const DelayRespMessage &message) noexcept
Process received Delay_Resp message.
MessageFlowStatistics get_statistics () const noexcept
Get message flow statistics.
MessageFlowHealthStatus get_health_status () const noexcept
Get message flow health status.
bool is_running () const noexcept
Check if message flow is running.
void reset () noexcept
Reset all statistics.
Detailed Description
Message Flow Integration Coordinator.
Orchestrates end-to-end message processing:
Announce messages → BMCA coordinator → State transitions
Sync messages → Sync coordinator → Servo controller
Provides unified interface for message handling with health monitoring and error detection across the complete synchronization pipeline.
Thread Safety: Not thread-safe. Caller must ensure serialized access. Real-Time: All operations use bounded execution time (no dynamic allocation).
Definition at line 157 of file message_flow_integration.hpp.
Constructor & Destructor Documentation
MessageFlowCoordinator()
IEEE::_1588::PTP::_2019::MessageFlowCoordinator::MessageFlowCoordinator (Integration::BMCAIntegration & bmca, SyncIntegration & sync, servo::ServoIntegration & servo, Clocks::PtpPort & port) explicit noexcept
Construct message flow coordinator.
Parameters
bmca BMCA integration coordinator (must outlive this object)
sync Sync integration coordinator (must outlive this object)
servo Servo integration controller (must outlive this object)
port PTP port for state management (must outlive this object)
Definition at line 25 of file message_flow_integration.cpp.
Member Function Documentation
configure()
Types::PTPError IEEE::_1588::PTP::_2019::MessageFlowCoordinator::configure (const MessageFlowConfiguration & config) noexcept
Configure message flow coordinator.
Parameters
config Configuration parameters
Returns
Success if configuration valid
Definition at line 49 of file message_flow_integration.cpp.
References IEEE::_1588::PTP::_2019::Types::Invalid_Parameter, and IEEE::_1588::PTP::_2019::Types::Success.
get_health_status()
MessageFlowHealthStatus IEEE::_1588::PTP::_2019::MessageFlowCoordinator::get_health_status () const noexcept
Get message flow health status.
Returns
Current health status with component rollup
Definition at line 294 of file message_flow_integration.cpp.
References IEEE::_1588::PTP::_2019::MessageFlowStatistics::announce_errors, IEEE::_1588::PTP::_2019::MessageFlowHealthStatus::announce_flow_active, IEEE::_1588::PTP::_2019::MessageFlowStatistics::announce_interval_ns, IEEE::_1588::PTP::_2019::MessageFlowStatistics::announce_received, IEEE::_1588::PTP::_2019::MessageFlowConfiguration::announce_timeout_ns, IEEE::_1588::PTP::_2019::MessageFlowHealthStatus::bmca_healthy, IEEE::_1588::PTP::_2019::MessageFlowHealthStatus::bmca_operational, IEEE::_1588::PTP::_2019::MessageFlowStatistics::bmca_triggered, IEEE::_1588::PTP::_2019::MessageFlowHealthStatus::Critical, IEEE::_1588::PTP::_2019::MessageFlowHealthStatus::Degraded, IEEE::_1588::PTP::_2019::MessageFlowHealthStatus::Healthy, IEEE::_1588::PTP::_2019::MessageFlowStatistics::invalid_messages, IEEE::_1588::PTP::_2019::servo::ServoIntegration::is_running(), IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::is_running(), IEEE::_1588::PTP::_2019::SyncIntegration::is_running(), IEEE::_1588::PTP::_2019::MessageFlowStatistics::last_sync_time_ns, IEEE::_1588::PTP::_2019::MessageFlowHealthStatus::message, IEEE::_1588::PTP::_2019::MessageFlowStatistics::servo_adjustments, IEEE::_1588::PTP::_2019::MessageFlowHealthStatus::servo_healthy, IEEE::_1588::PTP::_2019::MessageFlowHealthStatus::servo_operational, IEEE::_1588::PTP::_2019::MessageFlowHealthStatus::status, IEEE::_1588::PTP::_2019::MessageFlowStatistics::sync_errors, IEEE::_1588::PTP::_2019::MessageFlowHealthStatus::sync_flow_active, IEEE::_1588::PTP::_2019::MessageFlowHealthStatus::sync_healthy, IEEE::_1588::PTP::_2019::MessageFlowStatistics::sync_interval_ns, IEEE::_1588::PTP::_2019::MessageFlowStatistics::sync_received, IEEE::_1588::PTP::_2019::MessageFlowConfiguration::sync_timeout_ns, IEEE::_1588::PTP::_2019::MessageFlowHealthStatus::timestamp_ns, and IEEE::_1588::PTP::_2019::MessageFlowHealthStatus::within_timing_spec.
get_statistics()
MessageFlowStatistics IEEE::_1588::PTP::_2019::MessageFlowCoordinator::get_statistics () const inline noexcept
Get message flow statistics.
Returns
Current statistics snapshot
Definition at line 268 of file message_flow_integration.hpp.
is_running()
bool IEEE::_1588::PTP::_2019::MessageFlowCoordinator::is_running () const inline noexcept
Check if message flow is running.
Returns
true if started and processing messages
Definition at line 284 of file message_flow_integration.hpp.
process_announce_message()
Types::PTPError IEEE::_1588::PTP::_2019::MessageFlowCoordinator::process_announce_message (const AnnounceMessage & message, std::uint64_t reception_timestamp_ns) noexcept
Process received Announce message.
Flow: Validate → Extract foreign master info → Trigger BMCA
Parameters
message Announce message to process
reception_timestamp_ns Time message was received (local clock)
Returns
Success if processed successfully
Note
Triggers BMCA execution if enabled in configuration
See also
IEEE 1588-2019, Section 13.5 "Announce message"
IEEE 1588-2019, Section 9.3 "Best master clock algorithm"
Definition at line 116 of file message_flow_integration.cpp.
References IEEE::_1588::PTP::_2019::Types::State_Error, and IEEE::_1588::PTP::_2019::Types::Success.
process_delay_resp_message()
Types::PTPError IEEE::_1588::PTP::_2019::MessageFlowCoordinator::process_delay_resp_message (const DelayRespMessage & message) noexcept
Process received Delay_Resp message.
Flow: Validate → Calculate path delay → Update sync coordinator
Parameters
message Delay_Resp message to process
Returns
Success if processed successfully
See also
IEEE 1588-2019, Section 13.7 "Delay_Resp message"
Definition at line 261 of file message_flow_integration.cpp.
References IEEE::_1588::PTP::_2019::Types::State_Error, and IEEE::_1588::PTP::_2019::Types::Success.
process_follow_up_message()
Types::PTPError IEEE::_1588::PTP::_2019::MessageFlowCoordinator::process_follow_up_message (const FollowUpMessage & message) noexcept
Process received Follow_Up message.
Flow: Validate → Pair with Sync → Calculate precise offset
Parameters
message Follow_Up message to process
Returns
Success if processed successfully
Note
Must follow corresponding Sync message
See also
IEEE 1588-2019, Section 13.4 "Follow_Up message"
Definition at line 228 of file message_flow_integration.cpp.
References IEEE::_1588::PTP::_2019::Types::State_Error, and IEEE::_1588::PTP::_2019::Types::Success.
process_sync_message()
Types::PTPError IEEE::_1588::PTP::_2019::MessageFlowCoordinator::process_sync_message (const SyncMessage & message, std::uint64_t reception_timestamp_ns) noexcept
Process received Sync message.
Flow: Validate → Record timestamp → Calculate offset → Servo adjust
Parameters
message Sync message to process
reception_timestamp_ns Time message was received (local clock)
Returns
Success if processed successfully
Note
Triggers servo adjustment if enabled in configuration
See also
IEEE 1588-2019, Section 13.3 "Sync message"
IEEE 1588-2019, Section 11 "Synchronization mechanisms"
Definition at line 178 of file message_flow_integration.cpp.
References IEEE::_1588::PTP::_2019::Types::State_Error, and IEEE::_1588::PTP::_2019::Types::Success.
reset()
void IEEE::_1588::PTP::_2019::MessageFlowCoordinator::reset () noexcept
Reset all statistics.
Clears message flow statistics. Does not reset component statistics.
Definition at line 104 of file message_flow_integration.cpp.
References IEEE::_1588::PTP::_2019::MessageFlowStatistics::reset().
start()
Types::PTPError IEEE::_1588::PTP::_2019::MessageFlowCoordinator::start () noexcept
Start message flow processing.
Enables message handling and component coordination.
Returns
Success if started successfully
Definition at line 65 of file message_flow_integration.cpp.
References IEEE::_1588::PTP::_2019::MessageFlowStatistics::reset(), IEEE::_1588::PTP::_2019::servo::ServoIntegration::start(), IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::start(), IEEE::_1588::PTP::_2019::SyncIntegration::start(), IEEE::_1588::PTP::_2019::Types::State_Error, IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::stop(), IEEE::_1588::PTP::_2019::SyncIntegration::stop(), and IEEE::_1588::PTP::_2019::Types::Success.
stop()
void IEEE::_1588::PTP::_2019::MessageFlowCoordinator::stop () noexcept
Stop message flow processing.
Disables message handling. Does not stop underlying components.
Definition at line 100 of file message_flow_integration.cpp.
The documentation for this class was generated from the following files:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/message_flow_integration.hpp
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/src/message_flow_integration.cpp
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/src/message_flow_integration_bup.cpp