IEEE 1588-2019 PTP Library: IEEE::_1588::_2019::ProfileResult Struct Reference
IEEE::_1588::_2019::ProfileResult Struct Reference
Simple Result type for profile operations.
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/profile.hpp>
Public Member Functions
bool is_success () const
Static Public Member Functions
static ProfileResult ok ()
static ProfileResult fail ()
Public Attributes
bool success
Detailed Description
Simple Result type for profile operations.
Definition at line 149 of file profile.hpp.
Member Function Documentation
fail()
static ProfileResult IEEE::_1588::_2019::ProfileResult::fail () inline static
Definition at line 155 of file profile.hpp.
Referenced by IEEE::_1588::_2019::ProfileConfiguration::validate().
is_success()
bool IEEE::_1588::_2019::ProfileResult::is_success () const inline
Definition at line 152 of file profile.hpp.
References success.
ok()
static ProfileResult IEEE::_1588::_2019::ProfileResult::ok () inline static
Definition at line 154 of file profile.hpp.
Referenced by apply_profile(), and IEEE::_1588::_2019::ProfileConfiguration::validate().
Member Data Documentation
success
bool IEEE::_1588::_2019::ProfileResult::success
Definition at line 150 of file profile.hpp.
Referenced by is_success().
The documentation for this struct was generated from the following file:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/profile.hpp