IEEE 1588-2019 PTP Library: detail Namespace Reference
detail Namespace Reference
Functions
constexpr std::uint16_t bswap16 (std::uint16_t x) noexcept
constexpr std::uint32_t bswap32 (std::uint32_t x) noexcept
constexpr std::uint16_t host_to_be16 (std::uint16_t x) noexcept
constexpr std::uint16_t be16_to_host (std::uint16_t x) noexcept
constexpr std::uint32_t host_to_be32 (std::uint32_t x) noexcept
constexpr std::uint32_t be32_to_host (std::uint32_t x) noexcept
Variables
constexpr bool is_little_endian = true
Function Documentation
be16_to_host()
constexpr std::uint16_t detail::be16_to_host (std::uint16_t x) constexpr noexcept
Definition at line 43 of file messages.hpp.
References bswap16(), and is_little_endian.
Referenced by IEEE::_1588::PTP::_2019::ManagementTLV::getManagementId(), IEEE::_1588::PTP::_2019::CommonHeader::isTwoStep(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_announce(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_management(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_signaling(), IEEE::_1588::PTP::_2019::CommonHeader::validate(), IEEE::_1588::PTP::_2019::AnnounceBody::validate(), and IEEE::_1588::PTP::_2019::TLVHeader::validate().
be32_to_host()
constexpr std::uint32_t detail::be32_to_host (std::uint32_t x) constexpr noexcept
Definition at line 49 of file messages.hpp.
References bswap32(), and is_little_endian.
bswap16()
constexpr std::uint16_t detail::bswap16 (std::uint16_t x) constexpr noexcept
Definition at line 29 of file messages.hpp.
Referenced by be16_to_host(), and host_to_be16().
bswap32()
constexpr std::uint32_t detail::bswap32 (std::uint32_t x) constexpr noexcept
Definition at line 30 of file messages.hpp.
Referenced by be32_to_host(), and host_to_be32().
host_to_be16()
constexpr std::uint16_t detail::host_to_be16 (std::uint16_t x) constexpr noexcept
Definition at line 40 of file messages.hpp.
References bswap16(), and is_little_endian.
Referenced by IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::initialize(), and IEEE::_1588::PTP::_2019::ManagementTLV::setManagementId().
host_to_be32()
constexpr std::uint32_t detail::host_to_be32 (std::uint32_t x) constexpr noexcept
Definition at line 46 of file messages.hpp.
References bswap32(), and is_little_endian.
Variable Documentation
is_little_endian
constexpr bool detail::is_little_endian = true constexpr
Definition at line 36 of file messages.hpp.
Referenced by be16_to_host(), be32_to_host(), host_to_be16(), and host_to_be32().