IEEE 1588-2019 PTP Library: Common::utils::logging Namespace Reference
Common::utils::logging Namespace Reference
Typedefs
using LogSink = void(*)(Level level, const char *component, std::uint32_t code, const char *message)
Enumerations
enum class Level : std::uint8_t { Debug = 0 , Info = 1 , Warn = 2 , Error = 3 }
Functions
LogSink & sink_ref () noexcept
void set_sink (LogSink sink) noexcept
LogSink get_sink () noexcept
void log (Level level, const char *component, std::uint32_t code, const char *message) noexcept
void debug (const char *component, std::uint32_t code, const char *message) noexcept
void info (const char *component, std::uint32_t code, const char *message) noexcept
void warn (const char *component, std::uint32_t code, const char *message) noexcept
void error (const char *component, std::uint32_t code, const char *message) noexcept
Typedef Documentation
LogSink
using Common::utils::logging::LogSink = typedef void(*)(Level level, const char* component, std::uint32_t code, const char* message)
Definition at line 23 of file logger.hpp.
Enumeration Type Documentation
Level
enum class Common::utils::logging::Level : std::uint8_t strong
Enumerator
Debug
Info
Warn
Error
Definition at line 19 of file logger.hpp.
Function Documentation
debug()
void Common::utils::logging::debug (const char * component, std::uint32_t code, const char * message) inline noexcept
Definition at line 39 of file logger.hpp.
References Debug, and log().
Referenced by IEEE::_1588::PTP::_2019::Clocks::SynchronizationData::calculateOffset(), and IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_follow_up().
error()
void Common::utils::logging::error (const char * component, std::uint32_t code, const char * message) inline noexcept
Definition at line 48 of file logger.hpp.
References Error, and log().
get_sink()
LogSink Common::utils::logging::get_sink () inline noexcept
Definition at line 32 of file logger.hpp.
References sink_ref().
info()
void Common::utils::logging::info (const char * component, std::uint32_t code, const char * message) inline noexcept
Definition at line 42 of file logger.hpp.
References Info, and log().
Referenced by IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_follow_up().
log()
void Common::utils::logging::log (Level level, const char * component, std::uint32_t code, const char * message) inline noexcept
Definition at line 34 of file logger.hpp.
References sink_ref().
Referenced by debug(), error(), info(), and warn().
set_sink()
void Common::utils::logging::set_sink (LogSink sink) inline noexcept
Definition at line 31 of file logger.hpp.
References sink_ref().
sink_ref()
LogSink & Common::utils::logging::sink_ref () inline noexcept
Definition at line 26 of file logger.hpp.
Referenced by get_sink(), log(), and set_sink().
warn()
void Common::utils::logging::warn (const char * component, std::uint32_t code, const char * message) inline noexcept
Definition at line 45 of file logger.hpp.
References log(), and Warn.
Referenced by IEEE::_1588::PTP::_2019::Clocks::SynchronizationData::calculateOffset().