IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::Types::TimeInterval Struct Reference
IEEE::_1588::PTP::_2019::Types::TimeInterval Struct Reference
Time Interval - scaled nanoseconds for time intervals.
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/types.hpp>
Public Member Functions
constexpr double toNanoseconds () const noexcept
Convert to nanoseconds.
Static Public Member Functions
static constexpr TimeInterval fromNanoseconds (double ns) noexcept
Create from nanoseconds.
static constexpr TimeInterval fromNanosecondsUnbiased (double ns) noexcept
Create from nanoseconds with unbiased (banker's) rounding to nearest even for 2^-16 scaling.
Public Attributes
Integer64 scaled_nanoseconds
Time interval in units of 2^-16 nanoseconds.
Detailed Description
Time Interval - scaled nanoseconds for time intervals.
Deterministic design: All operations are constexpr with bounded execution time.
Definition at line 292 of file types.hpp.
Member Function Documentation
fromNanoseconds()
static constexpr TimeInterval IEEE::_1588::PTP::_2019::Types::TimeInterval::fromNanoseconds (double ns) inline static constexpr noexcept
Create from nanoseconds.
Note
Deterministic: O(1) execution time, no blocking
Definition at line 307 of file types.hpp.
Referenced by IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_delay_resp(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_follow_up(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_pdelay_resp(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_pdelay_resp_follow_up(), and IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_sync().
fromNanosecondsUnbiased()
static constexpr TimeInterval IEEE::_1588::PTP::_2019::Types::TimeInterval::fromNanosecondsUnbiased (double ns) inline static constexpr noexcept
Create from nanoseconds with unbiased (banker's) rounding to nearest even for 2^-16 scaling.
Parameters
ns Nanoseconds as double
Returns
TimeInterval with scaled_nanoseconds rounded using nearest-even
Note
FM-014 mitigation helper (optional compensation). If fractional part is exactly 0.5 in scaled units, rounds to even.
Definition at line 317 of file types.hpp.
toNanoseconds()
constexpr double IEEE::_1588::PTP::_2019::Types::TimeInterval::toNanoseconds () const inline constexpr noexcept
Convert to nanoseconds.
Note
Deterministic: O(1) execution time, no blocking
Definition at line 299 of file types.hpp.
Referenced by IEEE::_1588::PTP::_2019::Clocks::SynchronizationData::calculateOffset().
Member Data Documentation
scaled_nanoseconds
Integer64 IEEE::_1588::PTP::_2019::Types::TimeInterval::scaled_nanoseconds
Time interval in units of 2^-16 nanoseconds.
Definition at line 293 of file types.hpp.
Referenced by IEEE::_1588::PTP::_2019::Clocks::SynchronizationData::calculateOffset().
The documentation for this struct was generated from the following file:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/types.hpp