IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock Class Reference
IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock Class Reference
Ordinary Clock State Machine.
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/clocks.hpp>
Public Member Functions
OrdinaryClock (const PortConfiguration &port_config, const StateCallbacks &callbacks) noexcept
Construct Ordinary Clock.
OrdinaryClock (const OrdinaryClock &)=delete
Non-copyable for deterministic resource management.
OrdinaryClock & operator= (const OrdinaryClock &)=delete
OrdinaryClock (OrdinaryClock &&) noexcept=default
Movable for efficient initialization.
OrdinaryClock & operator= (OrdinaryClock &&) noexcept=default
~OrdinaryClock () noexcept=default
Destructor ensures clean resource release.
Types::PTPResult< void > initialize () noexcept
Initialize ordinary clock.
Types::PTPResult< void > start () noexcept
Start clock operation.
Types::PTPResult< void > stop () noexcept
Stop clock operation.
Types::PTPResult< void > process_message (std::uint8_t message_type, const void *message_data, std::size_t message_size, const Types::Timestamp &rx_timestamp) noexcept
Process received PTP message.
Types::PTPResult< void > tick (const Types::Timestamp &current_time) noexcept
Execute periodic clock tasks.
constexpr PtpPort & get_port () noexcept
Get the single PTP port (non-const)
constexpr const PtpPort & get_port () const noexcept
Get the single PTP port (const)
constexpr ClockType get_clock_type () const noexcept
Get clock type.
constexpr bool is_master () const noexcept
Check if clock is master.
constexpr bool is_slave () const noexcept
Check if clock is slave.
constexpr bool is_synchronized () const noexcept
Check if clock is synchronized.
constexpr const TimePropertiesDataSet & get_time_properties_data_set () const noexcept
Get time properties data set per IEEE 1588-2019 Section 8.2.4.
Detailed Description
Ordinary Clock State Machine.
IEEE 1588-2019 Ordinary Clock implementation with single port and deterministic state management per Section 6.5.2.
Definition at line 837 of file clocks.hpp.
Constructor & Destructor Documentation
OrdinaryClock() [1/3]
IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::OrdinaryClock (const PortConfiguration & port_config, const StateCallbacks & callbacks) explicit noexcept
Construct Ordinary Clock.
Parameters
port_config Configuration for the single PTP port
callbacks Hardware abstraction callbacks
Definition at line 1330 of file clocks.cpp.
OrdinaryClock() [2/3]
IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::OrdinaryClock (const OrdinaryClock &) delete
Non-copyable for deterministic resource management.
OrdinaryClock() [3/3]
IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::OrdinaryClock (OrdinaryClock &&) default noexcept
Movable for efficient initialization.
~OrdinaryClock()
IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::~OrdinaryClock () default noexcept
Destructor ensures clean resource release.
Member Function Documentation
get_clock_type()
constexpr ClockType IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::get_clock_type () const inline constexpr noexcept
Get clock type.
Definition at line 911 of file clocks.hpp.
get_port() [1/2]
constexpr const PtpPort & IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::get_port () const inline constexpr noexcept
Get the single PTP port (const)
Definition at line 908 of file clocks.hpp.
get_port() [2/2]
constexpr PtpPort & IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::get_port () inline constexpr noexcept
Get the single PTP port (non-const)
Definition at line 905 of file clocks.hpp.
get_time_properties_data_set()
constexpr const TimePropertiesDataSet & IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::get_time_properties_data_set () const inline constexpr noexcept
Get time properties data set per IEEE 1588-2019 Section 8.2.4.
Definition at line 923 of file clocks.hpp.
References IEEE::_1588::PTP::_2019::Clocks::PtpPort::get_time_properties_data_set().
initialize()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::initialize () noexcept
Initialize ordinary clock.
Returns
Success/failure result
Definition at line 1335 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Clocks::PtpPort::initialize().
is_master()
constexpr bool IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::is_master () const inline constexpr noexcept
Check if clock is master.
Definition at line 914 of file clocks.hpp.
References IEEE::_1588::PTP::_2019::Clocks::PtpPort::is_master().
is_slave()
constexpr bool IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::is_slave () const inline constexpr noexcept
Check if clock is slave.
Definition at line 917 of file clocks.hpp.
References IEEE::_1588::PTP::_2019::Clocks::PtpPort::is_slave().
is_synchronized()
constexpr bool IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::is_synchronized () const inline constexpr noexcept
Check if clock is synchronized.
Definition at line 920 of file clocks.hpp.
References IEEE::_1588::PTP::_2019::Clocks::PtpPort::is_synchronized().
operator=() [1/2]
OrdinaryClock & IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::operator= (const OrdinaryClock &) delete
operator=() [2/2]
OrdinaryClock & IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::operator= (OrdinaryClock &&) default noexcept
process_message()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::process_message (std::uint8_t message_type, const void * message_data, std::size_t message_size, const Types::Timestamp & rx_timestamp) noexcept
Process received PTP message.
Parameters
message_type Type of PTP message
message_data Message data buffer
message_size Size of message data
rx_timestamp Hardware receive timestamp
Returns
Success/failure result
Definition at line 1347 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), IEEE::_1588::PTP::_2019::Types::INVALID_MESSAGE_SIZE, and IEEE::_1588::PTP::_2019::Types::UNSUPPORTED_MESSAGE.
start()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::start () noexcept
Start clock operation.
Returns
Success/failure result
Definition at line 1339 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Clocks::PtpPort::start().
stop()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::stop () noexcept
Stop clock operation.
Returns
Success/failure result
Definition at line 1343 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Clocks::PtpPort::stop().
tick()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::tick (const Types::Timestamp & current_time) noexcept
Execute periodic clock tasks.
Parameters
current_time Current system time
Returns
Success/failure result
Definition at line 1398 of file clocks.cpp.
The documentation for this class was generated from the following files:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/clocks.hpp
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/src/clocks.cpp