IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::Clocks Namespace Reference
IEEE::_1588::PTP::_2019::Clocks Namespace Reference
IEEE 1588-2019 Clock State Machines.
Classes
class BoundaryClock
Boundary Clock State Machine.
struct CurrentDataSet
Current Data Set per IEEE 1588-2019 Section 8.2.2.
struct DefaultDataSet
Default Data Set per IEEE 1588-2019 Section 8.2.1.
class OrdinaryClock
Ordinary Clock State Machine.
struct ParentDataSet
Parent Data Set per IEEE 1588-2019 Section 8.2.3.
struct PortConfiguration
PTP Port Configuration.
struct PortDataSet
PTP Port Data Set per IEEE 1588-2019 Section 8.2.5.
struct PortStatistics
PTP Port Statistics.
class PtpPort
PTP Port State Machine.
struct StateCallbacks
State Machine Callbacks.
struct SynchronizationData
Clock synchronization information.
struct TimePropertiesDataSet
Time Properties Data Set per IEEE 1588-2019 Section 8.2.4.
class TransparentClock
Transparent Clock State Machine.
Typedefs
using AnnounceMessage = IEEE::_1588::PTP::_2019::AnnounceMessage
using SyncMessage = IEEE::_1588::PTP::_2019::SyncMessage
using FollowUpMessage = IEEE::_1588::PTP::_2019::FollowUpMessage
using DelayReqMessage = IEEE::_1588::PTP::_2019::DelayReqMessage
using DelayRespMessage = IEEE::_1588::PTP::_2019::DelayRespMessage
Enumerations
enum class StateEvent : std::uint8_t {
POWERUP = 0x00 , INITIALIZE = 0x01 , FAULT_DETECTED = 0x02 , FAULT_CLEARED = 0x03 ,
DESIGNATED_ENABLED = 0x04 , DESIGNATED_DISABLED = 0x05 , RS_MASTER = 0x06 , RS_GRAND_MASTER = 0x07 ,
RS_SLAVE = 0x08 , RS_PASSIVE = 0x09 , ANNOUNCE_RECEIPT_TIMEOUT = 0x0A , SYNCHRONIZATION_FAULT = 0x0B ,
QUALIFICATION_TIMEOUT = 0x0C
}
State Machine Events per IEEE 1588-2019 Section 9.2.6.
enum class BMCADecision : std::uint8_t {
BETTER_MASTER = 0x00 , BETTER_BY_TOPOLOGY = 0x01 , SAME_MASTER = 0x02 , WORSE_BY_TOPOLOGY = 0x03 ,
WORSE_MASTER = 0x04
}
Best Master Clock Algorithm Decision.
enum class PortRole : std::uint8_t { MASTER = 0x00 , SLAVE = 0x01 , PASSIVE = 0x02 , DISABLED = 0x03 }
Port Role Designation per IEEE 1588-2019 Section 9.3.3.
Functions
Types::PTPResult< void > parse_tlv_header (const std::uint8_t *buffer, std::size_t buffer_size, TLVHeader &header) noexcept
Parse TLV header from buffer.
Types::PTPResult< void > parse_management_tlv (const std::uint8_t *buffer, std::size_t buffer_size, ManagementTLV &mgmt_tlv) noexcept
Parse Management TLV from buffer.
Types::PTPResult< void > validate_tlv_length (std::uint16_t tlv_length, std::size_t available_size) noexcept
Validate TLV length field against buffer bounds.
Detailed Description
IEEE 1588-2019 Clock State Machines.
Implementation of clock state machines per IEEE 1588-2019 Sections 9.2, 10.2, and 10.3 with time-sensitive design patterns.
Typedef Documentation
AnnounceMessage
using IEEE::_1588::PTP::_2019::Clocks::AnnounceMessage = typedef IEEE::_1588::PTP::_2019::AnnounceMessage
Definition at line 65 of file clocks.hpp.
DelayReqMessage
using IEEE::_1588::PTP::_2019::Clocks::DelayReqMessage = typedef IEEE::_1588::PTP::_2019::DelayReqMessage
Definition at line 68 of file clocks.hpp.
DelayRespMessage
using IEEE::_1588::PTP::_2019::Clocks::DelayRespMessage = typedef IEEE::_1588::PTP::_2019::DelayRespMessage
Definition at line 69 of file clocks.hpp.
FollowUpMessage
using IEEE::_1588::PTP::_2019::Clocks::FollowUpMessage = typedef IEEE::_1588::PTP::_2019::FollowUpMessage
Definition at line 67 of file clocks.hpp.
SyncMessage
using IEEE::_1588::PTP::_2019::Clocks::SyncMessage = typedef IEEE::_1588::PTP::_2019::SyncMessage
Definition at line 66 of file clocks.hpp.
Enumeration Type Documentation
BMCADecision
enum class IEEE::_1588::PTP::_2019::Clocks::BMCADecision : std::uint8_t strong
Best Master Clock Algorithm Decision.
Result of BMCA comparison per IEEE 1588-2019 Section 9.3
Enumerator
BETTER_MASTER
Foreign master is better.
BETTER_BY_TOPOLOGY
Foreign master better by topology.
SAME_MASTER
Same master clock.
WORSE_BY_TOPOLOGY
Foreign master worse by topology.
WORSE_MASTER
Foreign master is worse.
Definition at line 95 of file clocks.hpp.
PortRole
enum class IEEE::_1588::PTP::_2019::Clocks::PortRole : std::uint8_t strong
Port Role Designation per IEEE 1588-2019 Section 9.3.3.
Port role assignment after BMCA decision
Enumerator
MASTER
Master port role.
SLAVE
Slave port role.
PASSIVE
Passive port role.
DISABLED
Disabled port role.
Definition at line 107 of file clocks.hpp.
StateEvent
enum class IEEE::_1588::PTP::_2019::Clocks::StateEvent : std::uint8_t strong
State Machine Events per IEEE 1588-2019 Section 9.2.6.
Events that trigger state transitions in PTP port state machines
Enumerator
POWERUP
Power-up or initialization.
INITIALIZE
Initialize event.
FAULT_DETECTED
Fault detected.
FAULT_CLEARED
Fault cleared.
DESIGNATED_ENABLED
Port designated and enabled.
DESIGNATED_DISABLED
Port designated but disabled.
RS_MASTER
Recommended State: Master.
RS_GRAND_MASTER
Recommended State: Grand Master.
RS_SLAVE
Recommended State: Slave.
RS_PASSIVE
Recommended State: Passive.
ANNOUNCE_RECEIPT_TIMEOUT
Announce receipt timeout.
SYNCHRONIZATION_FAULT
Synchronization fault.
QUALIFICATION_TIMEOUT
Master qualification timeout.
Definition at line 75 of file clocks.hpp.
Function Documentation
parse_management_tlv()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::parse_management_tlv (const std::uint8_t * buffer, std::size_t buffer_size, ManagementTLV & mgmt_tlv) inline noexcept
Parse Management TLV from buffer.
Parameters
buffer Input buffer containing Management TLV payload (after TLV header)
buffer_size Size of input buffer
mgmt_tlv Output Management TLV structure
Returns
Success/failure result
Note
IEEE 1588-2019 Section 15.5.4.1 - MANAGEMENT TLV format
Definition at line 459 of file clocks.hpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), IEEE::_1588::PTP::_2019::Types::INVALID_LENGTH, and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
parse_tlv_header()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::parse_tlv_header (const std::uint8_t * buffer, std::size_t buffer_size, TLVHeader & header) inline noexcept
Parse TLV header from buffer.
Parameters
buffer Input buffer containing TLV data
buffer_size Size of input buffer
header Output TLV header structure
Returns
Success/failure result
Note
IEEE 1588-2019 Section 14 - TLV format
Definition at line 437 of file clocks.hpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), and IEEE::_1588::PTP::_2019::Types::INVALID_LENGTH.
validate_tlv_length()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::validate_tlv_length (std::uint16_t tlv_length, std::size_t available_size) inline noexcept
Validate TLV length field against buffer bounds.
Parameters
tlv_length Length field from TLV header (host byte order)
available_size Available buffer size for TLV payload
Returns
Success/failure result
Note
IEEE 1588-2019 Section 14.2 - lengthField validation
Definition at line 479 of file clocks.hpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), IEEE::_1588::PTP::_2019::Types::INVALID_LENGTH, and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().