IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::AnnounceBody Struct Reference
IEEE::_1588::PTP::_2019::AnnounceBody Struct Reference
Announce message body for Best Master Clock Algorithm.
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/messages.hpp>
Public Member Functions
PTPResult< void > validate () const noexcept
Validate announce message fields.
Public Attributes
Timestamp originTimestamp
std::int16_t currentUtcOffset
std::uint8_t reserved
std::uint8_t grandmasterPriority1
std::uint8_t grandmasterClockClass
std::uint8_t grandmasterClockAccuracy
std::uint16_t grandmasterClockVariance
std::uint8_t grandmasterPriority2
ClockIdentity grandmasterIdentity
std::uint16_t stepsRemoved
std::uint8_t timeSource
Detailed Description
Announce message body for Best Master Clock Algorithm.
Contains clock quality and identity information for master selection. Follows IEEE 1588-2019 Section 13.5 format specification.
Definition at line 252 of file messages.hpp.
Member Function Documentation
validate()
PTPResult< void > IEEE::_1588::PTP::_2019::AnnounceBody::validate () const inline noexcept
Validate announce message fields.
Returns
PTPResult with validation status
Definition at line 286 of file messages.hpp.
References detail::be16_to_host(), IEEE::_1588::PTP::_2019::Types::PTPResult< T >::makeError(), stepsRemoved, and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
Member Data Documentation
currentUtcOffset
std::int16_t IEEE::_1588::PTP::_2019::AnnounceBody::currentUtcOffset
Definition at line 257 of file messages.hpp.
grandmasterClockAccuracy
std::uint8_t IEEE::_1588::PTP::_2019::AnnounceBody::grandmasterClockAccuracy
Definition at line 267 of file messages.hpp.
grandmasterClockClass
std::uint8_t IEEE::_1588::PTP::_2019::AnnounceBody::grandmasterClockClass
Definition at line 266 of file messages.hpp.
grandmasterClockVariance
std::uint16_t IEEE::_1588::PTP::_2019::AnnounceBody::grandmasterClockVariance
Definition at line 268 of file messages.hpp.
grandmasterIdentity
ClockIdentity IEEE::_1588::PTP::_2019::AnnounceBody::grandmasterIdentity
Definition at line 274 of file messages.hpp.
grandmasterPriority1
std::uint8_t IEEE::_1588::PTP::_2019::AnnounceBody::grandmasterPriority1
Definition at line 263 of file messages.hpp.
grandmasterPriority2
std::uint8_t IEEE::_1588::PTP::_2019::AnnounceBody::grandmasterPriority2
Definition at line 271 of file messages.hpp.
originTimestamp
Timestamp IEEE::_1588::PTP::_2019::AnnounceBody::originTimestamp
Definition at line 254 of file messages.hpp.
reserved
std::uint8_t IEEE::_1588::PTP::_2019::AnnounceBody::reserved
Definition at line 260 of file messages.hpp.
stepsRemoved
std::uint16_t IEEE::_1588::PTP::_2019::AnnounceBody::stepsRemoved
Definition at line 277 of file messages.hpp.
Referenced by validate().
timeSource
std::uint8_t IEEE::_1588::PTP::_2019::AnnounceBody::timeSource
Definition at line 280 of file messages.hpp.
The documentation for this struct was generated from the following file:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/messages.hpp