IEEE 1588-2019 PTP Library: Common::utils::fi Namespace Reference
Common::utils::fi Namespace Reference
Namespaces
namespace detail
Functions
void reset () noexcept
void enable_offset_jitter (bool enable) noexcept
void set_offset_jitter_ns (long long ns) noexcept
bool is_offset_jitter_enabled () noexcept
long long get_offset_jitter_ns () noexcept
void force_bmca_tie_next (int count=1) noexcept
bool consume_bmca_tie_token () noexcept
void mark_bmca_tie_forced_observed (bool used) noexcept
bool was_bmca_tie_forced_and_clear () noexcept
Function Documentation
consume_bmca_tie_token()
bool Common::utils::fi::consume_bmca_tie_token () inline noexcept
Definition at line 68 of file fault_injection.hpp.
References Common::utils::fi::detail::bmca_tie_tokens().
enable_offset_jitter()
void Common::utils::fi::enable_offset_jitter (bool enable) inline noexcept
Definition at line 50 of file fault_injection.hpp.
References Common::utils::fi::detail::offset_jitter_enabled().
force_bmca_tie_next()
void Common::utils::fi::force_bmca_tie_next (int count = 1) inline noexcept
Definition at line 64 of file fault_injection.hpp.
References Common::utils::fi::detail::bmca_tie_tokens().
get_offset_jitter_ns()
long long Common::utils::fi::get_offset_jitter_ns () inline noexcept
Definition at line 59 of file fault_injection.hpp.
References Common::utils::fi::detail::offset_jitter_ns().
Referenced by IEEE::_1588::PTP::_2019::Clocks::SynchronizationData::calculateOffset().
is_offset_jitter_enabled()
bool Common::utils::fi::is_offset_jitter_enabled () inline noexcept
Definition at line 56 of file fault_injection.hpp.
References Common::utils::fi::detail::offset_jitter_enabled().
Referenced by IEEE::_1588::PTP::_2019::Clocks::SynchronizationData::calculateOffset(), and Common::utils::health::self_test().
mark_bmca_tie_forced_observed()
void Common::utils::fi::mark_bmca_tie_forced_observed (bool used) inline noexcept
Definition at line 80 of file fault_injection.hpp.
References Common::utils::fi::detail::bmca_tie_forced_observed().
reset()
void Common::utils::fi::reset () inline noexcept
Definition at line 42 of file fault_injection.hpp.
References Common::utils::fi::detail::bmca_tie_forced_observed(), Common::utils::fi::detail::bmca_tie_tokens(), Common::utils::fi::detail::offset_jitter_enabled(), and Common::utils::fi::detail::offset_jitter_ns().
set_offset_jitter_ns()
void Common::utils::fi::set_offset_jitter_ns (long long ns) inline noexcept
Definition at line 53 of file fault_injection.hpp.
References Common::utils::fi::detail::offset_jitter_ns().
was_bmca_tie_forced_and_clear()
bool Common::utils::fi::was_bmca_tie_forced_and_clear () inline noexcept
Definition at line 87 of file fault_injection.hpp.
References Common::utils::fi::detail::bmca_tie_forced_observed().