IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::Types::PortIdentity Struct Reference
IEEE::_1588::PTP::_2019::Types::PortIdentity Struct Reference
Port Identity - combination of clock identity and port number.
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/types.hpp>
Public Member Functions
bool operator== (const PortIdentity &other) const noexcept
Equality comparison.
bool operator< (const PortIdentity &other) const noexcept
Less-than comparison for ordering.
PTPResult< void > validate () const noexcept
Validate port identity fields.
Public Attributes
ClockIdentity clock_identity
Clock identifier.
PortNumber port_number
Port number.
Detailed Description
Port Identity - combination of clock identity and port number.
Deterministic design: POD structure with O(1) comparison operations.
Definition at line 246 of file types.hpp.
Member Function Documentation
operator<()
bool IEEE::_1588::PTP::_2019::Types::PortIdentity::operator< (const PortIdentity & other) const inline noexcept
Less-than comparison for ordering.
Note
Deterministic: O(1) execution time
Definition at line 263 of file types.hpp.
References clock_identity, and port_number.
operator==()
bool IEEE::_1588::PTP::_2019::Types::PortIdentity::operator== (const PortIdentity & other) const inline noexcept
Equality comparison.
Note
Deterministic: O(1) execution time
Definition at line 254 of file types.hpp.
References clock_identity, and port_number.
validate()
PTPResult< void > IEEE::_1588::PTP::_2019::Types::PortIdentity::validate () const inline noexcept
Validate port identity fields.
Returns
PTPResult indicating success or error
Note
Required for message validation compatibility
Definition at line 821 of file types.hpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::makeError(), port_number, IEEE::_1588::PTP::_2019::Types::Port_Number_Error, and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
Referenced by IEEE::_1588::PTP::_2019::DelayRespBody::validate(), IEEE::_1588::PTP::_2019::PdelayRespBody::validate(), and IEEE::_1588::PTP::_2019::PdelayRespFollowUpBody::validate().
Member Data Documentation
clock_identity
ClockIdentity IEEE::_1588::PTP::_2019::Types::PortIdentity::clock_identity
Clock identifier.
Definition at line 247 of file types.hpp.
Referenced by operator<(), and operator==().
port_number
PortNumber IEEE::_1588::PTP::_2019::Types::PortIdentity::port_number
Port number.
Definition at line 248 of file types.hpp.
Referenced by operator<(), operator==(), and validate().
The documentation for this struct was generated from the following file:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/types.hpp