IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::SyncIntegration Class Reference
IEEE::_1588::PTP::_2019::SyncIntegration Class Reference
Synchronization Integration Coordinator.
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/sync_integration.hpp>
Classes
struct Configuration
Configuration for synchronization behavior.
Public Member Functions
SyncIntegration (Clocks::PtpPort &port) noexcept
Construct synchronization coordinator.
Types::PTPResult< void > configure (const Configuration &config) noexcept
Configure synchronization behavior.
Types::PTPResult< void > start () noexcept
Start synchronization monitoring.
Types::PTPResult< void > stop () noexcept
Stop synchronization monitoring.
Types::PTPResult< void > tick (const Types::Timestamp &current_time) noexcept
Periodic tick for sync monitoring and servo control.
Types::PTPResult< void > sample_now (const Types::Timestamp &current_time) noexcept
Force immediate synchronization sample.
const SyncStatistics & get_statistics () const noexcept
Get current synchronization statistics.
SyncHealthStatus get_health_status () const noexcept
Get current health status.
void reset () noexcept
Reset all statistics and health indicators.
bool is_running () const noexcept
Check if coordinator is running.
Detailed Description
Synchronization Integration Coordinator.
Manages sync/offset/delay measurement integration with clock servo. Coordinates IEEE 1588-2019 synchronization mechanisms (E2E or P2P) and provides observability through metrics and health monitoring.
Usage:
SyncIntegration sync_coordinator(port);
sync_coordinator.configure(config);
sync_coordinator.start();
// In main loop
sync_coordinator.tick(current_time);
// Query sync quality
auto health = sync_coordinator.get_health_status();
auto stats = sync_coordinator.get_statistics();
Definition at line 117 of file sync_integration.hpp.
Constructor & Destructor Documentation
SyncIntegration()
IEEE::_1588::PTP::_2019::SyncIntegration::SyncIntegration (Clocks::PtpPort & port) inline explicit noexcept
Construct synchronization coordinator.
Parameters
port Reference to PtpPort being coordinated
Definition at line 154 of file sync_integration.hpp.
Member Function Documentation
configure()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::SyncIntegration::configure (const Configuration & config) inline noexcept
Configure synchronization behavior.
Parameters
config Configuration parameters
Returns
Success if valid, failure otherwise
Definition at line 165 of file sync_integration.hpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), IEEE::_1588::PTP::_2019::Types::Invalid_Parameter, and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
get_health_status()
SyncHealthStatus IEEE::_1588::PTP::_2019::SyncIntegration::get_health_status () const inline noexcept
Get current health status.
Returns
Current health indicators
Definition at line 242 of file sync_integration.hpp.
get_statistics()
const SyncStatistics & IEEE::_1588::PTP::_2019::SyncIntegration::get_statistics () const inline noexcept
Get current synchronization statistics.
Returns
Reference to current statistics
Definition at line 234 of file sync_integration.hpp.
is_running()
bool IEEE::_1588::PTP::_2019::SyncIntegration::is_running () const inline noexcept
Check if coordinator is running.
Definition at line 259 of file sync_integration.hpp.
Referenced by IEEE::_1588::PTP::_2019::MessageFlowCoordinator::get_health_status().
reset()
void IEEE::_1588::PTP::_2019::SyncIntegration::reset () inline noexcept
Reset all statistics and health indicators.
Definition at line 249 of file sync_integration.hpp.
References IEEE::_1588::PTP::_2019::SyncStatistics::reset().
sample_now()
Types::PTPResult< void > SyncIntegration::sample_now (const Types::Timestamp & current_time) noexcept
Force immediate synchronization sample.
Useful when Sync/Follow_Up/Delay_Resp received.
Parameters
current_time Current timestamp
Returns
Success if sample collected
Definition at line 44 of file sync_integration.cpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure().
start()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::SyncIntegration::start () inline noexcept
Start synchronization monitoring.
Returns
Success if started, failure if already running
Definition at line 177 of file sync_integration.hpp.
References IEEE::_1588::PTP::_2019::SyncHealthStatus::Critical, IEEE::_1588::PTP::_2019::SyncHealthStatus::delay_stable, IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), IEEE::_1588::PTP::_2019::SyncHealthStatus::measurements_valid, IEEE::_1588::PTP::_2019::SyncHealthStatus::message, IEEE::_1588::PTP::_2019::SyncHealthStatus::offset_within_spec, IEEE::_1588::PTP::_2019::SyncStatistics::reset(), IEEE::_1588::PTP::_2019::SyncHealthStatus::servo_locked, IEEE::_1588::PTP::_2019::Types::State_Error, IEEE::_1588::PTP::_2019::SyncHealthStatus::status, and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
Referenced by IEEE::_1588::PTP::_2019::MessageFlowCoordinator::start().
stop()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::SyncIntegration::stop () inline noexcept
Stop synchronization monitoring.
Returns
Success if stopped
Definition at line 200 of file sync_integration.hpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), IEEE::_1588::PTP::_2019::Types::State_Error, and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
Referenced by IEEE::_1588::PTP::_2019::MessageFlowCoordinator::start().
tick()
Types::PTPResult< void > SyncIntegration::tick (const Types::Timestamp & current_time) noexcept
Periodic tick for sync monitoring and servo control.
Samples offset and delay, updates statistics, triggers servo. Must be called regularly for accurate sync monitoring.
Parameters
current_time Current timestamp
Returns
Success if tick processed successfully
Definition at line 12 of file sync_integration.cpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
The documentation for this class was generated from the following files:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/sync_integration.hpp
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/src/sync_integration.cpp