IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::Types::PTPResult< T > Class Template Reference
IEEE::_1588::PTP::_2019::Types::PTPResult< T > Class Template Reference
Deterministic result type for operations that may fail.
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/types.hpp>
Public Member Functions
constexpr PTPResult (const T &value) noexcept
Construct successful result.
constexpr PTPResult (PTPError error) noexcept
Construct error result.
constexpr PTPResult (const PTPResult &other) noexcept
Copy constructor.
constexpr bool hasValue () const noexcept
Check if result contains a value.
constexpr bool isSuccess () const noexcept
constexpr bool hasError () const noexcept
Check if result contains an error.
constexpr const T & getValue () const noexcept
Get the value (only call if hasValue() returns true)
constexpr PTPError getError () const noexcept
Get the error code (only call if hasError() returns true)
constexpr T getValueOr (const T &default_value) const noexcept
Get value or return default if error.
constexpr bool is_success () const noexcept
Check if result is successful (alias for hasValue)
constexpr const T & get_value () const noexcept
Get the value (alias for getValue)
constexpr PTPError get_error () const noexcept
Get the error (alias for getError)
Static Public Member Functions
static constexpr PTPResult success (const T &value) noexcept
Create successful result (static method)
static constexpr PTPResult failure (PTPError error) noexcept
Create error result (static method)
static constexpr PTPResult makeError (PTPError error) noexcept
Create error result (alias for failure)
Detailed Description
template<typename T>
class IEEE::_1588::PTP::_2019::Types::PTPResult< T >
Deterministic result type for operations that may fail.
Template class providing error handling without exceptions. Suitable for time-sensitive systems with deterministic behavior.
Template Parameters
T The type of value returned on success
Definition at line 523 of file types.hpp.
Constructor & Destructor Documentation
PTPResult() [1/3]
template<typename T > constexpr IEEE::_1588::PTP::_2019::Types::PTPResult< T >::PTPResult (const T & value) inline explicit constexpr noexcept
Construct successful result.
Parameters
value The success value
Note
Deterministic: O(1) construction, no dynamic allocation
Definition at line 537 of file types.hpp.
PTPResult() [2/3]
template<typename T > constexpr IEEE::_1588::PTP::_2019::Types::PTPResult< T >::PTPResult (PTPError error) inline explicit constexpr noexcept
Construct error result.
Parameters
error The error code
Note
Deterministic: O(1) construction, no dynamic allocation
Definition at line 545 of file types.hpp.
PTPResult() [3/3]
template<typename T > constexpr IEEE::_1588::PTP::_2019::Types::PTPResult< T >::PTPResult (const PTPResult< T > & other) inline constexpr noexcept
Copy constructor.
Note
Deterministic: O(1) operation
Definition at line 552 of file types.hpp.
Member Function Documentation
failure()
template<typename T > static constexpr PTPResult IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure (PTPError error) inline static constexpr noexcept
Create error result (static method)
Parameters
error The error code
Returns
Error PTPResult
Note
Compatibility method for clock state machine API
Definition at line 655 of file types.hpp.
Referenced by IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::configure(), IEEE::_1588::PTP::_2019::SyncIntegration::configure(), IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::execute_bmca(), IEEE::_1588::PTP::_2019::Clocks::TransparentClock::forward_message(), IEEE::_1588::PTP::_2019::Clocks::parse_management_tlv(), IEEE::_1588::PTP::_2019::Clocks::parse_tlv_header(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_management(), IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::process_message(), IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::process_message(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_signaling(), IEEE::_1588::PTP::_2019::SyncIntegration::sample_now(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::set_announce_interval(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::set_sync_interval(), IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::start(), IEEE::_1588::PTP::_2019::SyncIntegration::start(), IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::stop(), IEEE::_1588::PTP::_2019::SyncIntegration::stop(), IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::tick(), IEEE::_1588::PTP::_2019::SyncIntegration::tick(), IEEE::_1588::PTP::_2019::TLVHeader::validate(), IEEE::_1588::PTP::_2019::ManagementMessageBody::validate(), and IEEE::_1588::PTP::_2019::Clocks::validate_tlv_length().
get_error()
template<typename T > constexpr PTPError IEEE::_1588::PTP::_2019::Types::PTPResult< T >::get_error () const inline constexpr noexcept
Get the error (alias for getError)
Returns
The error code
Note
Compatibility method for clock state machine API
Definition at line 635 of file types.hpp.
get_value()
template<typename T > constexpr const T & IEEE::_1588::PTP::_2019::Types::PTPResult< T >::get_value () const inline constexpr noexcept
Get the value (alias for getValue)
Returns
The success value
Note
Compatibility method for clock state machine API
Definition at line 626 of file types.hpp.
getError()
template<typename T > constexpr PTPError IEEE::_1588::PTP::_2019::Types::PTPResult< T >::getError () const inline constexpr noexcept
Get the error code (only call if hasError() returns true)
Returns
The error code
Note
Deterministic: O(1) access, caller must check hasError() first
Definition at line 596 of file types.hpp.
getValue()
template<typename T > constexpr const T & IEEE::_1588::PTP::_2019::Types::PTPResult< T >::getValue () const inline constexpr noexcept
Get the value (only call if hasValue() returns true)
Returns
The success value
Note
Deterministic: O(1) access, caller must check hasValue() first
Definition at line 587 of file types.hpp.
getValueOr()
template<typename T > constexpr T IEEE::_1588::PTP::_2019::Types::PTPResult< T >::getValueOr (const T & default_value) const inline constexpr noexcept
Get value or return default if error.
Parameters
default_value Value to return on error
Returns
The value or default
Note
Deterministic: O(1) operation
Definition at line 606 of file types.hpp.
hasError()
template<typename T > constexpr bool IEEE::_1588::PTP::_2019::Types::PTPResult< T >::hasError () const inline constexpr noexcept
Check if result contains an error.
Returns
true if error, false if successful
Note
Deterministic: O(1) check
Definition at line 578 of file types.hpp.
hasValue()
template<typename T > constexpr bool IEEE::_1588::PTP::_2019::Types::PTPResult< T >::hasValue () const inline constexpr noexcept
Check if result contains a value.
Returns
true if successful, false if error
Note
Deterministic: O(1) check
Definition at line 566 of file types.hpp.
is_success()
template<typename T > constexpr bool IEEE::_1588::PTP::_2019::Types::PTPResult< T >::is_success () const inline constexpr noexcept
Check if result is successful (alias for hasValue)
Returns
true if successful, false if error
Note
Compatibility method for clock state machine API
Definition at line 615 of file types.hpp.
isSuccess()
template<typename T > constexpr bool IEEE::_1588::PTP::_2019::Types::PTPResult< T >::isSuccess () const inline constexpr noexcept
Definition at line 571 of file types.hpp.
makeError()
template<typename T > static constexpr PTPResult IEEE::_1588::PTP::_2019::Types::PTPResult< T >::makeError (PTPError error) inline static constexpr noexcept
Create error result (alias for failure)
Parameters
error The error code
Returns
Error PTPResult
Note
Compatibility method for messages.hpp API
Definition at line 665 of file types.hpp.
Referenced by IEEE::_1588::PTP::_2019::CommonHeader::validate(), IEEE::_1588::PTP::_2019::AnnounceBody::validate(), IEEE::_1588::PTP::_2019::PdelayReqBody::validate(), IEEE::_1588::PTP::_2019::Types::Timestamp::validate(), and IEEE::_1588::PTP::_2019::Types::PortIdentity::validate().
success()
template<typename T > static constexpr PTPResult IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success (const T & value) inline static constexpr noexcept
Create successful result (static method)
Parameters
value The success value
Returns
Successful PTPResult
Note
Compatibility method for clock state machine API
Definition at line 645 of file types.hpp.
Referenced by IEEE::_1588::PTP::_2019::Clocks::SynchronizationData::calculateOffset(), IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::configure(), IEEE::_1588::PTP::_2019::SyncIntegration::configure(), IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::initialize(), IEEE::_1588::PTP::_2019::Clocks::TransparentClock::initialize(), IEEE::_1588::PTP::_2019::Clocks::parse_management_tlv(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_delay_req(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_delay_resp(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_follow_up(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_management(), IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::process_message(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_pdelay_req(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_pdelay_resp(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_pdelay_resp_follow_up(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_signaling(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_sync(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::set_announce_interval(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::set_sync_interval(), IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::start(), IEEE::_1588::PTP::_2019::Clocks::TransparentClock::start(), IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::start(), IEEE::_1588::PTP::_2019::SyncIntegration::start(), IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::stop(), IEEE::_1588::PTP::_2019::Clocks::TransparentClock::stop(), IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::stop(), IEEE::_1588::PTP::_2019::SyncIntegration::stop(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::tick(), IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::tick(), IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::tick(), IEEE::_1588::PTP::_2019::SyncIntegration::tick(), IEEE::_1588::PTP::_2019::CommonHeader::validate(), IEEE::_1588::PTP::_2019::AnnounceBody::validate(), IEEE::_1588::PTP::_2019::DelayReqBody::validate(), IEEE::_1588::PTP::_2019::PdelayReqBody::validate(), IEEE::_1588::PTP::_2019::TLVHeader::validate(), IEEE::_1588::PTP::_2019::ManagementMessageBody::validate(), IEEE::_1588::PTP::_2019::SignalingMessageBody::validate(), IEEE::_1588::PTP::_2019::Types::Timestamp::validate(), IEEE::_1588::PTP::_2019::Types::PortIdentity::validate(), and IEEE::_1588::PTP::_2019::Clocks::validate_tlv_length().
Member Data Documentation
error_
template<typename T > PTPError IEEE::_1588::PTP::_2019::Types::PTPResult< T >::error_
Error code when failed.
Definition at line 527 of file types.hpp.
value_
template<typename T > T IEEE::_1588::PTP::_2019::Types::PTPResult< T >::value_
Value when successful.
Definition at line 526 of file types.hpp.
The documentation for this class was generated from the following file:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/types.hpp