IEEE 1588-2019 PTP Library: Common::utils::metrics Namespace Reference
Common::utils::metrics Namespace Reference
Namespaces
namespace detail
Classes
struct Snapshot
Enumerations
enum class CounterId : std::uint16_t {
OffsetsComputed = 0 , BMCA_Selections = 1 , BMCA_CandidateUpdates = 2 , ValidationsFailed = 3 ,
ValidationsPassed = 4 , BMCA_LocalWins = 5 , BMCA_ForeignWins = 6 , BMCA_PassiveWins = 7 ,
COUNT
}
Functions
void reset () noexcept
void increment (CounterId id, std::uint64_t delta=1) noexcept
std::uint64_t get (CounterId id) noexcept
Snapshot snapshot () noexcept
Enumeration Type Documentation
CounterId
enum class Common::utils::metrics::CounterId : std::uint16_t strong
Enumerator
OffsetsComputed
BMCA_Selections
BMCA_CandidateUpdates
ValidationsFailed
ValidationsPassed
BMCA_LocalWins
BMCA_ForeignWins
BMCA_PassiveWins
COUNT
Definition at line 22 of file metrics.hpp.
Function Documentation
get()
std::uint64_t Common::utils::metrics::get (CounterId id) inline noexcept
Definition at line 63 of file metrics.hpp.
References Common::utils::metrics::detail::counters().
Referenced by IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_follow_up().
increment()
void Common::utils::metrics::increment (CounterId id, std::uint64_t delta = 1) inline noexcept
Definition at line 58 of file metrics.hpp.
References Common::utils::metrics::detail::counters().
Referenced by IEEE::_1588::PTP::_2019::Clocks::SynchronizationData::calculateOffset().
reset()
void Common::utils::metrics::reset () inline noexcept
Definition at line 53 of file metrics.hpp.
References Common::utils::metrics::detail::counters().
snapshot()
Snapshot Common::utils::metrics::snapshot () inline noexcept
Definition at line 68 of file metrics.hpp.
References BMCA_CandidateUpdates, BMCA_ForeignWins, BMCA_LocalWins, BMCA_PassiveWins, BMCA_Selections, Common::utils::metrics::Snapshot::bmcaCandidateUpdates, Common::utils::metrics::Snapshot::bmcaForeignWins, Common::utils::metrics::Snapshot::bmcaLocalWins, Common::utils::metrics::Snapshot::bmcaPassiveWins, Common::utils::metrics::Snapshot::bmcaSelections, Common::utils::metrics::detail::counters(), OffsetsComputed, Common::utils::metrics::Snapshot::offsetsComputed, ValidationsFailed, Common::utils::metrics::Snapshot::validationsFailed, ValidationsPassed, and Common::utils::metrics::Snapshot::validationsPassed.
Referenced by Common::utils::health::self_test().