IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::CommonHeader Struct Reference
IEEE::_1588::PTP::_2019::CommonHeader Struct Reference
Common PTP Message Header - present in all PTP messages.
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/messages.hpp>
Public Member Functions
constexpr MessageType getMessageType () const noexcept
Extract message type with zero-cost abstraction.
constexpr void setMessageType (MessageType type) noexcept
Set message type with deterministic execution.
constexpr std::uint8_t getVersion () const noexcept
Extract PTP version with compile-time optimization.
constexpr void setVersion (std::uint8_t version) noexcept
Set PTP version (typically 2 for IEEE 1588-2019)
bool isTwoStep () const noexcept
Check if two-step flag is set.
constexpr bool isEventMessage () const noexcept
Check if this is an event message requiring timestamping.
PTPResult< void > validate () const noexcept
Validate header consistency with deterministic checks.
Public Attributes
std::uint8_t transport_messageType
std::uint8_t reserved_version
std::uint16_t messageLength
std::uint8_t domainNumber
std::uint8_t minorVersionPTP
std::uint16_t flagField
CorrectionField correctionField
std::uint32_t messageTypeSpecific
PortIdentity sourcePortIdentity
std::uint16_t sequenceId
std::uint8_t controlField
std::int8_t logMessageInterval
Detailed Description
Common PTP Message Header - present in all PTP messages.
Fixed 34-byte header structure as specified in IEEE 1588-2019 Section 13.3. Designed for deterministic parsing with O(1) field access.
Note
Network byte order (big-endian) for all multi-byte fields
Hardware timestamping occurs at specific points during transmission/reception
Definition at line 116 of file messages.hpp.
Member Function Documentation
getMessageType()
constexpr MessageType IEEE::_1588::PTP::_2019::CommonHeader::getMessageType () const inline constexpr noexcept
Extract message type with zero-cost abstraction.
Returns
MessageType enum value
Note
Constexpr for compile-time optimization
Definition at line 162 of file messages.hpp.
References transport_messageType.
Referenced by isEventMessage().
getVersion()
constexpr std::uint8_t IEEE::_1588::PTP::_2019::CommonHeader::getVersion () const inline constexpr noexcept
Extract PTP version with compile-time optimization.
Returns
PTP version (should be 2 for IEEE 1588-2019)
Definition at line 180 of file messages.hpp.
References reserved_version.
Referenced by validate().
isEventMessage()
constexpr bool IEEE::_1588::PTP::_2019::CommonHeader::isEventMessage () const inline constexpr noexcept
Check if this is an event message requiring timestamping.
Returns
true if event message, false if general message
Note
Event messages: Sync, Delay_Req, Pdelay_Req, Pdelay_Resp
Definition at line 205 of file messages.hpp.
References getMessageType().
isTwoStep()
bool IEEE::_1588::PTP::_2019::CommonHeader::isTwoStep () const inline noexcept
Check if two-step flag is set.
Returns
true if two-step mode, false if one-step mode
Definition at line 196 of file messages.hpp.
References detail::be16_to_host(), flagField, and IEEE::_1588::PTP::_2019::Flags::TWO_STEP.
setMessageType()
constexpr void IEEE::_1588::PTP::_2019::CommonHeader::setMessageType (MessageType type) inline constexpr noexcept
Set message type with deterministic execution.
Parameters
type MessageType to set
Note
Preserves transport specific field (upper 4 bits)
Definition at line 171 of file messages.hpp.
References transport_messageType.
Referenced by IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::initialize(), and IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_delay_req().
setVersion()
constexpr void IEEE::_1588::PTP::_2019::CommonHeader::setVersion (std::uint8_t version) inline constexpr noexcept
Set PTP version (typically 2 for IEEE 1588-2019)
Parameters
version PTP version to set
Definition at line 188 of file messages.hpp.
References reserved_version.
Referenced by IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::initialize().
validate()
PTPResult< void > IEEE::_1588::PTP::_2019::CommonHeader::validate () const inline noexcept
Validate header consistency with deterministic checks.
Returns
PTPResult with validation status
Note
All validation checks have bounded execution time
Definition at line 218 of file messages.hpp.
References detail::be16_to_host(), getVersion(), IEEE::_1588::PTP::_2019::Types::PTPResult< T >::makeError(), messageLength, reserved_version, and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
Referenced by IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::validate().
Member Data Documentation
controlField
std::uint8_t IEEE::_1588::PTP::_2019::CommonHeader::controlField
Definition at line 148 of file messages.hpp.
Referenced by IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::initialize().
correctionField
CorrectionField IEEE::_1588::PTP::_2019::CommonHeader::correctionField
Definition at line 136 of file messages.hpp.
domainNumber
std::uint8_t IEEE::_1588::PTP::_2019::CommonHeader::domainNumber
Definition at line 127 of file messages.hpp.
Referenced by IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::initialize(), and IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_delay_req().
flagField
std::uint16_t IEEE::_1588::PTP::_2019::CommonHeader::flagField
Definition at line 133 of file messages.hpp.
Referenced by isTwoStep().
logMessageInterval
std::int8_t IEEE::_1588::PTP::_2019::CommonHeader::logMessageInterval
Definition at line 151 of file messages.hpp.
messageLength
std::uint16_t IEEE::_1588::PTP::_2019::CommonHeader::messageLength
Definition at line 124 of file messages.hpp.
Referenced by IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::initialize(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_delay_req(), and validate().
messageTypeSpecific
std::uint32_t IEEE::_1588::PTP::_2019::CommonHeader::messageTypeSpecific
Definition at line 139 of file messages.hpp.
minorVersionPTP
std::uint8_t IEEE::_1588::PTP::_2019::CommonHeader::minorVersionPTP
Definition at line 130 of file messages.hpp.
Referenced by IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::initialize().
reserved_version
std::uint8_t IEEE::_1588::PTP::_2019::CommonHeader::reserved_version
Definition at line 121 of file messages.hpp.
Referenced by getVersion(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_delay_req(), setVersion(), and validate().
sequenceId
std::uint16_t IEEE::_1588::PTP::_2019::CommonHeader::sequenceId
Definition at line 145 of file messages.hpp.
Referenced by IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_delay_req().
sourcePortIdentity
PortIdentity IEEE::_1588::PTP::_2019::CommonHeader::sourcePortIdentity
Definition at line 142 of file messages.hpp.
Referenced by IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::initialize(), and IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_delay_req().
transport_messageType
std::uint8_t IEEE::_1588::PTP::_2019::CommonHeader::transport_messageType
Definition at line 118 of file messages.hpp.
Referenced by getMessageType(), and setMessageType().
The documentation for this struct was generated from the following file:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/messages.hpp