IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::TLVHeader Struct Reference
IEEE::_1588::PTP::_2019::TLVHeader Struct Reference
TLV Header Structure (IEEE 1588-2019 Section 14)
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/messages.hpp>
Public Member Functions
PTPResult< void > validate () const noexcept
Validate TLV header.
Public Attributes
std::uint16_t tlvType
std::uint16_t lengthField
Detailed Description
TLV Header Structure (IEEE 1588-2019 Section 14)
Common header for all TLV entities. Consists of:
tlvType: 2 bytes (network byte order) - identifies TLV type
lengthField: 2 bytes (network byte order) - octets in valueField (excludes type/length)
Note
All multi-byte fields use network byte order (big-endian) per Section 7.1.2
Definition at line 613 of file messages.hpp.
Member Function Documentation
validate()
PTPResult< void > IEEE::_1588::PTP::_2019::TLVHeader::validate () const inline noexcept
Validate TLV header.
Returns
PTPResult with validation status
Definition at line 621 of file messages.hpp.
References detail::be16_to_host(), IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), lengthField, and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
Member Data Documentation
lengthField
std::uint16_t IEEE::_1588::PTP::_2019::TLVHeader::lengthField
Definition at line 615 of file messages.hpp.
Referenced by validate().
tlvType
std::uint16_t IEEE::_1588::PTP::_2019::TLVHeader::tlvType
Definition at line 614 of file messages.hpp.
The documentation for this struct was generated from the following file:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/messages.hpp