IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::PTPMessage< BodyType > Struct Template Reference
IEEE::_1588::PTP::_2019::PTPMessage< BodyType > Struct Template Reference
Complete PTP Message template combining header and body.
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/messages.hpp>
Public Member Functions
PTPResult< void > validate () const noexcept
Validate complete message structure.
void initialize (MessageType msgType, std::uint8_t domain, const PortIdentity &sourcePort) noexcept
Initialize message with proper defaults.
Static Public Member Functions
static constexpr std::size_t getMessageSize () noexcept
Get total message size.
Public Attributes
CommonHeader header
BodyType body
Detailed Description
template<typename BodyType>
struct IEEE::_1588::PTP::_2019::PTPMessage< BodyType >
Complete PTP Message template combining header and body.
Template-based approach for type-safe message handling with compile-time size validation and deterministic memory layout.
Template Parameters
BodyType Specific message body type
Definition at line 519 of file messages.hpp.
Member Function Documentation
getMessageSize()
template<typename BodyType > static constexpr std::size_t IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::getMessageSize () inline static constexpr noexcept
Get total message size.
Returns
Message size in bytes
Note
Constexpr for compile-time computation
Definition at line 542 of file messages.hpp.
Referenced by IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::initialize().
initialize()
template<typename BodyType > void IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::initialize (MessageType msgType, std::uint8_t domain, const PortIdentity & sourcePort) inline noexcept
Initialize message with proper defaults.
Parameters
msgType Message type to set
domain PTP domain number
sourcePort Source port identity
Definition at line 552 of file messages.hpp.
References IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::body, IEEE::_1588::PTP::_2019::CommonHeader::controlField, IEEE::_1588::PTP::_2019::CommonHeader::domainNumber, IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::getMessageSize(), IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::header, detail::host_to_be16(), IEEE::_1588::PTP::_2019::CommonHeader::messageLength, IEEE::_1588::PTP::_2019::CommonHeader::minorVersionPTP, IEEE::_1588::PTP::_2019::CommonHeader::setMessageType(), IEEE::_1588::PTP::_2019::CommonHeader::setVersion(), and IEEE::_1588::PTP::_2019::CommonHeader::sourcePortIdentity.
validate()
template<typename BodyType > PTPResult< void > IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::validate () const inline noexcept
Validate complete message structure.
Returns
PTPResult with validation status
Note
Validates both header and body with bounded execution time
Definition at line 528 of file messages.hpp.
References IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::body, IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::header, and IEEE::_1588::PTP::_2019::CommonHeader::validate().
Member Data Documentation
body
template<typename BodyType > BodyType IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::body
Definition at line 521 of file messages.hpp.
Referenced by IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::initialize(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_delay_req(), and IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::validate().
header
template<typename BodyType > CommonHeader IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::header
Definition at line 520 of file messages.hpp.
Referenced by IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::initialize(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_delay_req(), and IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::validate().
The documentation for this struct was generated from the following file:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/messages.hpp