IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::Clocks::SynchronizationData Struct Reference
IEEE::_1588::PTP::_2019::Clocks::SynchronizationData Struct Reference
Clock synchronization information.
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/clocks.hpp>
Public Member Functions
SynchronizationData () noexcept=default
Types::PTPResult< Types::TimeInterval > calculateOffset (const Types::Timestamp &sync_timestamp, const Types::Timestamp &sync_reception, const Types::Timestamp &delay_req_timestamp, const Types::Timestamp &delay_resp_timestamp) noexcept
Calculate offset from master using timestamps.
Public Attributes
Types::Timestamp masterTimeStamp
Master timestamp from Sync message.
Types::Timestamp slaveTimeStamp
Slave timestamp when Sync received.
Types::CorrectionField correction
Correction field from messages.
Types::TimeInterval offsetFromMaster
Calculated offset from master.
Types::TimeInterval meanPathDelay
Mean path delay to master.
Detailed Description
Clock synchronization information.
Definition at line 304 of file clocks.hpp.
Constructor & Destructor Documentation
SynchronizationData()
IEEE::_1588::PTP::_2019::Clocks::SynchronizationData::SynchronizationData () default noexcept
Member Function Documentation
calculateOffset()
Types::PTPResult< Types::TimeInterval > IEEE::_1588::PTP::_2019::Clocks::SynchronizationData::calculateOffset (const Types::Timestamp & sync_timestamp, const Types::Timestamp & sync_reception, const Types::Timestamp & delay_req_timestamp, const Types::Timestamp & delay_resp_timestamp) inline noexcept
Calculate offset from master using timestamps.
Parameters
sync_timestamp Master timestamp from Sync message
sync_reception Local timestamp when Sync was received
delay_req_timestamp Local timestamp when DelayReq was sent
delay_resp_timestamp Master timestamp from DelayResp message
Returns
Result containing calculated offset or error
Definition at line 321 of file clocks.hpp.
References Common::utils::logging::debug(), Common::utils::health::emit(), Common::utils::fi::get_offset_jitter_ns(), Common::utils::metrics::increment(), Common::utils::fi::is_offset_jitter_enabled(), Common::utils::config::is_rounding_compensation_enabled(), offsetFromMaster, Common::utils::metrics::OffsetsComputed, Common::utils::health::record_offset_ns(), IEEE::_1588::PTP::_2019::Types::TimeInterval::scaled_nanoseconds, IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success(), IEEE::_1588::PTP::_2019::Types::TimeInterval::toNanoseconds(), Common::utils::metrics::ValidationsFailed, Common::utils::metrics::ValidationsPassed, and Common::utils::logging::warn().
Member Data Documentation
correction
Types::CorrectionField IEEE::_1588::PTP::_2019::Clocks::SynchronizationData::correction
Correction field from messages.
Definition at line 307 of file clocks.hpp.
masterTimeStamp
Types::Timestamp IEEE::_1588::PTP::_2019::Clocks::SynchronizationData::masterTimeStamp
Master timestamp from Sync message.
Definition at line 305 of file clocks.hpp.
meanPathDelay
Types::TimeInterval IEEE::_1588::PTP::_2019::Clocks::SynchronizationData::meanPathDelay
Mean path delay to master.
Definition at line 309 of file clocks.hpp.
offsetFromMaster
Types::TimeInterval IEEE::_1588::PTP::_2019::Clocks::SynchronizationData::offsetFromMaster
Calculated offset from master.
Definition at line 308 of file clocks.hpp.
Referenced by calculateOffset().
slaveTimeStamp
Types::Timestamp IEEE::_1588::PTP::_2019::Clocks::SynchronizationData::slaveTimeStamp
Slave timestamp when Sync received.
Definition at line 306 of file clocks.hpp.
The documentation for this struct was generated from the following file:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/clocks.hpp