IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::Types::CorrectionField Struct Reference
IEEE::_1588::PTP::_2019::Types::CorrectionField Struct Reference
Correction Field - time correction in units of nanoseconds * 2^16.
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/types.hpp>
Public Member Functions
constexpr CorrectionField () noexcept
Default constructor.
constexpr CorrectionField (UInteger64 val) noexcept
Value constructor.
constexpr double toNanoseconds () const noexcept
Convert to nanoseconds.
CorrectionField (const TimeInterval &interval) noexcept
Constructor from TimeInterval (for static_cast support)
constexpr CorrectionField & operator+= (const CorrectionField &other) noexcept
Addition assignment operator.
constexpr CorrectionField operator<< (unsigned int shift) const noexcept
Left shift operator for scaling.
Static Public Member Functions
static constexpr CorrectionField fromNanoseconds (double ns) noexcept
Create from nanoseconds.
Public Attributes
UInteger64 value
Correction value in scaled nanoseconds.
Detailed Description
Correction Field - time correction in units of nanoseconds * 2^16.
Deterministic design: All operations are constexpr with bounded execution time. No dynamic allocation or blocking calls.
Definition at line 86 of file types.hpp.
Constructor & Destructor Documentation
CorrectionField() [1/3]
constexpr IEEE::_1588::PTP::_2019::Types::CorrectionField::CorrectionField () inline constexpr noexcept
Default constructor.
Definition at line 92 of file types.hpp.
Referenced by fromNanoseconds(), and operator<<().
CorrectionField() [2/3]
constexpr IEEE::_1588::PTP::_2019::Types::CorrectionField::CorrectionField (UInteger64 val) inline explicit constexpr noexcept
Value constructor.
Parameters
val Initial value
Definition at line 98 of file types.hpp.
CorrectionField() [3/3]
IEEE::_1588::PTP::_2019::Types::CorrectionField::CorrectionField (const TimeInterval & interval) inline explicit noexcept
Constructor from TimeInterval (for static_cast support)
CorrectionField constructor from TimeInterval.
Parameters
interval TimeInterval value
Note
Deterministic: O(1) execution time, defined after TimeInterval
Defined here after TimeInterval is complete
Definition at line 341 of file types.hpp.
Member Function Documentation
fromNanoseconds()
static constexpr CorrectionField IEEE::_1588::PTP::_2019::Types::CorrectionField::fromNanoseconds (double ns) inline static constexpr noexcept
Create from nanoseconds.
Parameters
ns Nanoseconds value
Returns
CorrectionField instance
Note
Deterministic: O(1) execution time, no blocking
Definition at line 115 of file types.hpp.
References CorrectionField().
operator+=()
constexpr CorrectionField & IEEE::_1588::PTP::_2019::Types::CorrectionField::operator+= (const CorrectionField & other) inline constexpr noexcept
Addition assignment operator.
Parameters
other CorrectionField to add
Returns
Reference to this CorrectionField
Note
Deterministic: O(1) execution time, for clocks.cpp compatibility
Definition at line 132 of file types.hpp.
References value.
operator<<()
constexpr CorrectionField IEEE::_1588::PTP::_2019::Types::CorrectionField::operator<< (unsigned int shift) const inline constexpr noexcept
Left shift operator for scaling.
Parameters
shift Number of bits to shift
Returns
New CorrectionField with shifted value
Note
Deterministic: O(1) execution time, for clocks.cpp compatibility
Definition at line 143 of file types.hpp.
References CorrectionField(), and value.
toNanoseconds()
constexpr double IEEE::_1588::PTP::_2019::Types::CorrectionField::toNanoseconds () const inline constexpr noexcept
Convert to nanoseconds.
Returns
Correction value in nanoseconds
Note
Deterministic: O(1) execution time, no blocking
Definition at line 105 of file types.hpp.
References value.
Member Data Documentation
value
UInteger64 IEEE::_1588::PTP::_2019::Types::CorrectionField::value
Correction value in scaled nanoseconds.
Definition at line 87 of file types.hpp.
Referenced by operator+=(), operator<<(), and toNanoseconds().
The documentation for this struct was generated from the following file:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/types.hpp