IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::Clocks::TransparentClock Class Reference
IEEE::_1588::PTP::_2019::Clocks::TransparentClock Class Reference
Transparent Clock State Machine.
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/clocks.hpp>
Public Types
enum class TransparentType : std::uint8_t { END_TO_END = 0x00 , PEER_TO_PEER = 0x01 }
Transparent Clock Types.
Public Member Functions
TransparentClock (TransparentType type, const std::array< PortConfiguration, MAX_PORTS > &port_configs, std::size_t port_count, const StateCallbacks &callbacks) noexcept
Construct Transparent Clock.
TransparentClock (const TransparentClock &)=delete
Non-copyable for deterministic resource management.
TransparentClock & operator= (const TransparentClock &)=delete
TransparentClock (TransparentClock &&) noexcept=default
Movable for efficient initialization.
TransparentClock & operator= (TransparentClock &&) noexcept=default
~TransparentClock () noexcept=default
Destructor ensures clean resource release.
Types::PTPResult< void > initialize () noexcept
Initialize transparent clock.
Types::PTPResult< void > start () noexcept
Start clock operation.
Types::PTPResult< void > stop () noexcept
Stop clock operation.
Types::PTPResult< void > forward_message (Types::PortNumber ingress_port, Types::PortNumber egress_port, void *message_data, std::size_t message_size, const Types::Timestamp &ingress_timestamp, const Types::Timestamp &egress_timestamp) noexcept
Forward PTP message with residence time correction.
constexpr TransparentType get_transparent_type () const noexcept
Get transparent clock type.
constexpr ClockType get_clock_type () const noexcept
Get clock type.
constexpr std::size_t get_port_count () const noexcept
Get number of active ports.
Static Public Attributes
static constexpr std::size_t MAX_PORTS = 16
Maximum ports for transparent clock.
Detailed Description
Transparent Clock State Machine.
IEEE 1588-2019 Transparent Clock implementation with residence time correction per Section 6.5.4 and 6.5.5.
Definition at line 1041 of file clocks.hpp.
Member Enumeration Documentation
TransparentType
enum class IEEE::_1588::PTP::_2019::Clocks::TransparentClock::TransparentType : std::uint8_t strong
Transparent Clock Types.
Enumerator
END_TO_END
End-to-End Transparent Clock (E2E TC)
PEER_TO_PEER
Peer-to-Peer Transparent Clock (P2P TC)
Definition at line 1048 of file clocks.hpp.
Constructor & Destructor Documentation
TransparentClock() [1/3]
IEEE::_1588::PTP::_2019::Clocks::TransparentClock::TransparentClock (TransparentType type, const std::array< PortConfiguration, MAX_PORTS > & port_configs, std::size_t port_count, const StateCallbacks & callbacks) explicit noexcept
Construct Transparent Clock.
Parameters
type Type of transparent clock (E2E or P2P)
port_configs Array of port configurations
port_count Number of active ports
callbacks Hardware abstraction callbacks
Definition at line 1571 of file clocks.cpp.
TransparentClock() [2/3]
IEEE::_1588::PTP::_2019::Clocks::TransparentClock::TransparentClock (const TransparentClock &) delete
Non-copyable for deterministic resource management.
TransparentClock() [3/3]
IEEE::_1588::PTP::_2019::Clocks::TransparentClock::TransparentClock (TransparentClock &&) default noexcept
Movable for efficient initialization.
~TransparentClock()
IEEE::_1588::PTP::_2019::Clocks::TransparentClock::~TransparentClock () default noexcept
Destructor ensures clean resource release.
Member Function Documentation
forward_message()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::TransparentClock::forward_message (Types::PortNumber ingress_port, Types::PortNumber egress_port, void * message_data, std::size_t message_size, const Types::Timestamp & ingress_timestamp, const Types::Timestamp & egress_timestamp) noexcept
Forward PTP message with residence time correction.
Parameters
ingress_port Port that received the message
egress_port Port to forward the message to
message_data Message data buffer (will be modified)
message_size Size of message data
ingress_timestamp Message ingress timestamp
egress_timestamp Message egress timestamp
Returns
Success/failure result
Definition at line 1599 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure().
get_clock_type()
constexpr ClockType IEEE::_1588::PTP::_2019::Clocks::TransparentClock::get_clock_type () const inline constexpr noexcept
Get clock type.
Definition at line 1121 of file clocks.hpp.
get_port_count()
constexpr std::size_t IEEE::_1588::PTP::_2019::Clocks::TransparentClock::get_port_count () const inline constexpr noexcept
Get number of active ports.
Definition at line 1128 of file clocks.hpp.
get_transparent_type()
constexpr TransparentType IEEE::_1588::PTP::_2019::Clocks::TransparentClock::get_transparent_type () const inline constexpr noexcept
Get transparent clock type.
Definition at line 1118 of file clocks.hpp.
initialize()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::TransparentClock::initialize () noexcept
Initialize transparent clock.
Returns
Success/failure result
Definition at line 1585 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
operator=() [1/2]
TransparentClock & IEEE::_1588::PTP::_2019::Clocks::TransparentClock::operator= (const TransparentClock &) delete
operator=() [2/2]
TransparentClock & IEEE::_1588::PTP::_2019::Clocks::TransparentClock::operator= (TransparentClock &&) default noexcept
start()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::TransparentClock::start () noexcept
Start clock operation.
Returns
Success/failure result
Definition at line 1591 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
stop()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::TransparentClock::stop () noexcept
Stop clock operation.
Returns
Success/failure result
Definition at line 1595 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
Member Data Documentation
MAX_PORTS
constexpr std::size_t IEEE::_1588::PTP::_2019::Clocks::TransparentClock::MAX_PORTS = 16 static constexpr
Maximum ports for transparent clock.
Definition at line 1043 of file clocks.hpp.
The documentation for this class was generated from the following files:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/clocks.hpp
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/src/clocks.cpp