IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::Clocks::PtpPort Class Reference
IEEE::_1588::PTP::_2019::Clocks::PtpPort Class Reference
PTP Port State Machine.
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/clocks.hpp>
Public Member Functions
PtpPort () noexcept
Default constructor for container initialization (non-operational)
PtpPort (const PortConfiguration &config, const StateCallbacks &callbacks) noexcept
Construct PTP port with deterministic configuration.
PtpPort (const PtpPort &)=delete
Non-copyable for deterministic resource management.
PtpPort & operator= (const PtpPort &)=delete
PtpPort (PtpPort &&) noexcept=default
Movable for efficient initialization.
PtpPort & operator= (PtpPort &&) noexcept=default
~PtpPort () noexcept=default
Destructor ensures clean resource release.
Types::PTPResult< void > initialize () noexcept
Initialize port state machine.
Types::PTPResult< void > start () noexcept
Start port operation.
Types::PTPResult< void > stop () noexcept
Stop port operation.
Types::PTPResult< void > process_event (StateEvent event) noexcept
Process state machine event.
Types::PTPResult< void > process_announce (const AnnounceMessage &message) noexcept
Process received Announce message.
Types::PTPResult< void > process_sync (const SyncMessage &message, const Types::Timestamp &rx_timestamp) noexcept
Process received Sync message.
Types::PTPResult< void > process_follow_up (const FollowUpMessage &message) noexcept
Process received Follow_Up message.
Types::PTPResult< void > process_delay_req (const DelayReqMessage &message, const Types::Timestamp &rx_timestamp) noexcept
Process received Delay_Req message.
Types::PTPResult< void > process_delay_resp (const DelayRespMessage &message) noexcept
Process received Delay_Resp message.
Types::PTPResult< void > process_pdelay_req (const PdelayReqMessage &message, const Types::Timestamp &rx_timestamp) noexcept
Process received Pdelay_Req message (peer delay request)
Types::PTPResult< void > process_pdelay_resp (const PdelayRespMessage &message, const Types::Timestamp &rx_timestamp) noexcept
Process received Pdelay_Resp message (peer delay response)
Types::PTPResult< void > process_pdelay_resp_follow_up (const PdelayRespFollowUpMessage &message) noexcept
Process received Pdelay_Resp_Follow_Up message (precise t3 timestamp)
Types::PTPResult< void > process_management (const ManagementMessage &message, std::uint8_t *response_buffer, std::size_t &response_size) noexcept
Process Management message (dataset GET/SET operations)
Types::PTPResult< void > process_signaling (const SignalingMessage &message, std::uint8_t *response_buffer, std::size_t &response_size) noexcept
Process Signaling message (unicast negotiation, PATH_TRACE, etc.)
Types::PTPResult< void > tick (const Types::Timestamp &current_time) noexcept
Execute periodic state machine tasks.
constexpr PortState get_state () const noexcept
Get current port state.
constexpr const Types::PortIdentity & get_identity () const noexcept
Get port identity.
constexpr const PortStatistics & get_statistics () const noexcept
Get current statistics.
constexpr const PortConfiguration & get_configuration () const noexcept
Get port configuration.
constexpr const CurrentDataSet & get_current_data_set () const noexcept
Get current data set.
constexpr const ParentDataSet & get_parent_data_set () const noexcept
Get parent data set.
constexpr const TimePropertiesDataSet & get_time_properties_data_set () const noexcept
Get time properties data set per IEEE 1588-2019 Section 8.2.4.
constexpr const DefaultDataSet & get_default_data_set () const noexcept
Get default data set per IEEE 1588-2019 Section 8.2.1.
constexpr const PortDataSet & get_port_data_set () const noexcept
Get port data set (for dataset/read observability tests)
constexpr bool is_master () const noexcept
Check if port is in master role.
constexpr bool is_slave () const noexcept
Check if port is in slave role.
constexpr bool is_synchronized () const noexcept
Check if port is synchronized.
Types::PTPResult< void > set_announce_interval (std::uint8_t log_interval) noexcept
Update announce interval.
Types::PTPResult< void > set_sync_interval (std::uint8_t log_interval) noexcept
Update sync interval.
void clear_statistics () noexcept
Clear all statistics counters.
Detailed Description
PTP Port State Machine.
Implementation of IEEE 1588-2019 port state machine with deterministic state transitions and bounded execution time.
Implements state machine per IEEE 1588-2019 Figure 9-1 with:
Deterministic state transitions
Non-blocking message processing
Bounded memory usage
Hardware timestamping integration
Definition at line 504 of file clocks.hpp.
Constructor & Destructor Documentation
PtpPort() [1/4]
IEEE::_1588::PTP::_2019::Clocks::PtpPort::PtpPort () noexcept
Default constructor for container initialization (non-operational)
Definition at line 43 of file clocks.cpp.
PtpPort() [2/4]
IEEE::_1588::PTP::_2019::Clocks::PtpPort::PtpPort (const PortConfiguration & config, const StateCallbacks & callbacks) explicit noexcept
Construct PTP port with deterministic configuration.
Parameters
config Port configuration (must be valid)
callbacks Hardware abstraction callbacks
Definition at line 51 of file clocks.cpp.
PtpPort() [3/4]
IEEE::_1588::PTP::_2019::Clocks::PtpPort::PtpPort (const PtpPort &) delete
Non-copyable for deterministic resource management.
PtpPort() [4/4]
IEEE::_1588::PTP::_2019::Clocks::PtpPort::PtpPort (PtpPort &&) default noexcept
Movable for efficient initialization.
~PtpPort()
IEEE::_1588::PTP::_2019::Clocks::PtpPort::~PtpPort () default noexcept
Destructor ensures clean resource release.
Member Function Documentation
clear_statistics()
void IEEE::_1588::PTP::_2019::Clocks::PtpPort::clear_statistics () inline noexcept
Clear all statistics counters.
Definition at line 734 of file clocks.hpp.
References IEEE::_1588::PTP::_2019::Clocks::PortStatistics::reset().
get_configuration()
constexpr const PortConfiguration & IEEE::_1588::PTP::_2019::Clocks::PtpPort::get_configuration () const inline constexpr noexcept
Get port configuration.
Definition at line 678 of file clocks.hpp.
get_current_data_set()
constexpr const CurrentDataSet & IEEE::_1588::PTP::_2019::Clocks::PtpPort::get_current_data_set () const inline constexpr noexcept
Get current data set.
Definition at line 681 of file clocks.hpp.
get_default_data_set()
constexpr const DefaultDataSet & IEEE::_1588::PTP::_2019::Clocks::PtpPort::get_default_data_set () const inline constexpr noexcept
Get default data set per IEEE 1588-2019 Section 8.2.1.
Definition at line 692 of file clocks.hpp.
get_identity()
constexpr const Types::PortIdentity & IEEE::_1588::PTP::_2019::Clocks::PtpPort::get_identity () const inline constexpr noexcept
Get port identity.
Definition at line 670 of file clocks.hpp.
References IEEE::_1588::PTP::_2019::Clocks::PortDataSet::port_identity.
get_parent_data_set()
constexpr const ParentDataSet & IEEE::_1588::PTP::_2019::Clocks::PtpPort::get_parent_data_set () const inline constexpr noexcept
Get parent data set.
Definition at line 684 of file clocks.hpp.
get_port_data_set()
constexpr const PortDataSet & IEEE::_1588::PTP::_2019::Clocks::PtpPort::get_port_data_set () const inline constexpr noexcept
Get port data set (for dataset/read observability tests)
Definition at line 697 of file clocks.hpp.
get_state()
constexpr PortState IEEE::_1588::PTP::_2019::Clocks::PtpPort::get_state () const inline constexpr noexcept
Get current port state.
Definition at line 667 of file clocks.hpp.
References IEEE::_1588::PTP::_2019::Clocks::PortDataSet::port_state.
get_statistics()
constexpr const PortStatistics & IEEE::_1588::PTP::_2019::Clocks::PtpPort::get_statistics () const inline constexpr noexcept
Get current statistics.
Definition at line 675 of file clocks.hpp.
get_time_properties_data_set()
constexpr const TimePropertiesDataSet & IEEE::_1588::PTP::_2019::Clocks::PtpPort::get_time_properties_data_set () const inline constexpr noexcept
Get time properties data set per IEEE 1588-2019 Section 8.2.4.
Definition at line 687 of file clocks.hpp.
Referenced by IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::get_time_properties_data_set().
initialize()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::PtpPort::initialize () noexcept
Initialize port state machine.
Returns
Success/failure result
Postcondition
Port state is INITIALIZING
Definition at line 124 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Clocks::PortDataSet::port_state, and IEEE::_1588::PTP::_2019::Clocks::PortStatistics::reset().
Referenced by IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::initialize().
is_master()
constexpr bool IEEE::_1588::PTP::_2019::Clocks::PtpPort::is_master () const inline constexpr noexcept
Check if port is in master role.
Definition at line 700 of file clocks.hpp.
References IEEE::_1588::PTP::_2019::Clocks::PortDataSet::port_state.
Referenced by IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::is_master().
is_slave()
constexpr bool IEEE::_1588::PTP::_2019::Clocks::PtpPort::is_slave () const inline constexpr noexcept
Check if port is in slave role.
Definition at line 705 of file clocks.hpp.
References IEEE::_1588::PTP::_2019::Clocks::PortDataSet::port_state.
Referenced by IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::is_slave().
is_synchronized()
constexpr bool IEEE::_1588::PTP::_2019::Clocks::PtpPort::is_synchronized () const inline constexpr noexcept
Check if port is synchronized.
Definition at line 711 of file clocks.hpp.
References IEEE::_1588::PTP::_2019::Clocks::PortDataSet::port_state.
Referenced by IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::is_synchronized().
operator=() [1/2]
PtpPort & IEEE::_1588::PTP::_2019::Clocks::PtpPort::operator= (const PtpPort &) delete
operator=() [2/2]
PtpPort & IEEE::_1588::PTP::_2019::Clocks::PtpPort::operator= (PtpPort &&) default noexcept
process_announce()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_announce (const AnnounceMessage & message) noexcept
Process received Announce message.
Parameters
message Validated Announce message
Returns
Success/failure result
Definition at line 415 of file clocks.cpp.
References detail::be16_to_host(), IEEE::_1588::PTP::_2019::Flags::CURRENT_UTC_OFFSET_VALID, IEEE::_1588::PTP::_2019::Flags::FREQUENCY_TRACEABLE, IEEE::_1588::PTP::_2019::Flags::LI_59, IEEE::_1588::PTP::_2019::Flags::LI_61, IEEE::_1588::PTP::_2019::Flags::PTP_TIMESCALE, and IEEE::_1588::PTP::_2019::Flags::TIME_TRACEABLE.
Referenced by IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::process_message().
process_delay_req()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_delay_req (const DelayReqMessage & message, const Types::Timestamp & rx_timestamp) noexcept
Process received Delay_Req message.
Parameters
message Validated Delay_Req message
rx_timestamp Receive timestamp from hardware
Returns
Success/failure result
Definition at line 511 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::body, IEEE::_1588::PTP::_2019::CommonHeader::domainNumber, IEEE::_1588::PTP::_2019::PTPMessage< BodyType >::header, IEEE::_1588::PTP::_2019::CommonHeader::messageLength, IEEE::_1588::PTP::_2019::CommonHeader::reserved_version, IEEE::_1588::PTP::_2019::CommonHeader::sequenceId, IEEE::_1588::PTP::_2019::CommonHeader::setMessageType(), IEEE::_1588::PTP::_2019::CommonHeader::sourcePortIdentity, IEEE::_1588::PTP::_2019::Types::Success, and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
Referenced by IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::process_message().
process_delay_resp()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_delay_resp (const DelayRespMessage & message) noexcept
Process received Delay_Resp message.
Parameters
message Validated Delay_Resp message
Returns
Success/failure result
Definition at line 562 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Types::CLOCK_IDENTITY_LENGTH, IEEE::_1588::PTP::_2019::Types::TimeInterval::fromNanoseconds(), and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
Referenced by IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::process_message().
process_event()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_event (StateEvent event) noexcept
Process state machine event.
Parameters
event State machine event to process
Returns
Success/failure result
Note
Bounded execution time, non-blocking
Definition at line 165 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Clocks::ANNOUNCE_RECEIPT_TIMEOUT, IEEE::_1588::PTP::_2019::Clocks::DESIGNATED_DISABLED, IEEE::_1588::PTP::_2019::Clocks::DESIGNATED_ENABLED, IEEE::_1588::PTP::_2019::Clocks::FAULT_CLEARED, IEEE::_1588::PTP::_2019::Clocks::FAULT_DETECTED, IEEE::_1588::PTP::_2019::Clocks::INITIALIZE, IEEE::_1588::PTP::_2019::Clocks::QUALIFICATION_TIMEOUT, IEEE::_1588::PTP::_2019::Clocks::RS_GRAND_MASTER, IEEE::_1588::PTP::_2019::Clocks::RS_MASTER, IEEE::_1588::PTP::_2019::Clocks::RS_PASSIVE, IEEE::_1588::PTP::_2019::Clocks::RS_SLAVE, and IEEE::_1588::PTP::_2019::Clocks::SYNCHRONIZATION_FAULT.
process_follow_up()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_follow_up (const FollowUpMessage & message) noexcept
Process received Follow_Up message.
Parameters
message Validated Follow_Up message
Returns
Success/failure result
Definition at line 474 of file clocks.cpp.
References Common::utils::logging::debug(), IEEE::_1588::PTP::_2019::Types::TimeInterval::fromNanoseconds(), Common::utils::metrics::get(), Common::utils::logging::info(), IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success(), and Common::utils::metrics::ValidationsFailed.
Referenced by IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::process_message().
process_management()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_management (const ManagementMessage & message, std::uint8_t * response_buffer, std::size_t & response_size) noexcept
Process Management message (dataset GET/SET operations)
Parameters
message Management message to process
response_buffer Buffer to store response (if GET operation)
response_size Size of response buffer / bytes written on success
Returns
Success/failure result
Note
IEEE 1588-2019 Section 15 - Management messages
This is a minimal implementation supporting basic GET operations
Definition at line 665 of file clocks.cpp.
References detail::be16_to_host(), IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), IEEE::_1588::PTP::_2019::ManagementAction::GET, IEEE::_1588::PTP::_2019::Types::INVALID_LENGTH, IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success(), and IEEE::_1588::PTP::_2019::Types::UNSUPPORTED_MESSAGE.
process_pdelay_req()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_pdelay_req (const PdelayReqMessage & message, const Types::Timestamp & rx_timestamp) noexcept
Process received Pdelay_Req message (peer delay request)
Parameters
message Validated Pdelay_Req message
rx_timestamp Receive timestamp from hardware (t2)
Returns
Success/failure result
Note
IEEE 1588-2019 Section 11.4 - Peer delay mechanism
Definition at line 590 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
process_pdelay_resp()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_pdelay_resp (const PdelayRespMessage & message, const Types::Timestamp & rx_timestamp) noexcept
Process received Pdelay_Resp message (peer delay response)
Parameters
message Validated Pdelay_Resp message (contains t2)
rx_timestamp Receive timestamp from hardware (t4)
Returns
Success/failure result
Note
IEEE 1588-2019 Section 11.4 - Peer delay mechanism
Definition at line 606 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Types::CLOCK_IDENTITY_LENGTH, IEEE::_1588::PTP::_2019::Types::TimeInterval::fromNanoseconds(), and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
process_pdelay_resp_follow_up()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_pdelay_resp_follow_up (const PdelayRespFollowUpMessage & message) noexcept
Process received Pdelay_Resp_Follow_Up message (precise t3 timestamp)
Parameters
message Validated Pdelay_Resp_Follow_Up message (contains t3)
Returns
Success/failure result
Note
IEEE 1588-2019 Section 11.4.3 - Two-step peer delay
Definition at line 642 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Types::TimeInterval::fromNanoseconds(), and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
process_signaling()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_signaling (const SignalingMessage & message, std::uint8_t * response_buffer, std::size_t & response_size) noexcept
Process Signaling message (unicast negotiation, PATH_TRACE, etc.)
Parameters
message Signaling message to process
response_buffer Buffer to store response (if needed)
response_size Size of response buffer / bytes written on success
Returns
Success/failure result
Note
IEEE 1588-2019 Section 13.10 - Signaling messages
IEEE 1588-2019 Section 16 - Optional features (unicast, path trace)
This is a minimal implementation supporting basic TLV parsing
Definition at line 711 of file clocks.cpp.
References detail::be16_to_host(), IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), IEEE::_1588::PTP::_2019::Types::INVALID_LENGTH, and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
process_sync()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_sync (const SyncMessage & message, const Types::Timestamp & rx_timestamp) noexcept
Process received Sync message.
Parameters
message Validated Sync message
rx_timestamp Receive timestamp from hardware
Returns
Success/failure result
Definition at line 456 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Types::TimeInterval::fromNanoseconds(), and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
Referenced by IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::process_message().
set_announce_interval()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::PtpPort::set_announce_interval (std::uint8_t log_interval) noexcept
Update announce interval.
Parameters
log_interval Log base 2 interval value
Returns
Success/failure result
Definition at line 1304 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), IEEE::_1588::PTP::_2019::Types::Invalid_Parameter, and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
set_sync_interval()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::PtpPort::set_sync_interval (std::uint8_t log_interval) noexcept
Update sync interval.
Parameters
log_interval Log base 2 interval value
Returns
Success/failure result
Definition at line 1315 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), IEEE::_1588::PTP::_2019::Types::Invalid_Parameter, and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
start()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::PtpPort::start () noexcept
Start port operation.
Returns
Success/failure result
Precondition
Port must be initialized
Definition at line 151 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Clocks::PortDataSet::port_state, and IEEE::_1588::PTP::_2019::Types::State_Error.
Referenced by IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::start().
stop()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::PtpPort::stop () noexcept
Stop port operation.
Returns
Success/failure result
Postcondition
Port enters appropriate quiescent state
Definition at line 160 of file clocks.cpp.
Referenced by IEEE::_1588::PTP::_2019::Clocks::OrdinaryClock::stop().
tick()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::PtpPort::tick (const Types::Timestamp & current_time) noexcept
Execute periodic state machine tasks.
Parameters
current_time Current system time
Returns
Success/failure result
Note
Must be called at regular intervals (e.g., every 125ms)
Definition at line 758 of file clocks.cpp.
References Common::utils::health::emit(), and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
The documentation for this class was generated from the following files:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/clocks.hpp
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/src/clocks.cpp