IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::ManagementMessageBody Struct Reference
IEEE::_1588::PTP::_2019::ManagementMessageBody Struct Reference
Management Message Body (IEEE 1588-2019 Section 15.5.3)
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/messages.hpp>
Public Member Functions
constexpr std::uint8_t getActionField () const noexcept
Get action field value from reserved_actionField byte.
constexpr void setActionField (std::uint8_t action) noexcept
Set action field value in reserved_actionField byte.
PTPResult< void > validate () const noexcept
Validate management message body.
Public Attributes
PortIdentity targetPortIdentity
std::uint8_t startingBoundaryHops
std::uint8_t boundaryHops
std::uint8_t reserved_actionField
std::uint8_t reserved
Detailed Description
Management Message Body (IEEE 1588-2019 Section 15.5.3)
Management message structure following common header (34 bytes). Total management-specific fields: 16 bytes before TLVs.
Structure (bytes relative to start of body, after 34-byte common header):
Bytes 0-9: targetPortIdentity (10 bytes)
Byte 10: startingBoundaryHops
Byte 11: boundaryHops
Byte 12: reserved (4 bits) + actionField (4 bits)
Byte 13: reserved
Bytes 14+: TLV entities (variable length)
Note
All multi-byte fields use network byte order (big-endian)
Definition at line 664 of file messages.hpp.
Member Function Documentation
getActionField()
constexpr std::uint8_t IEEE::_1588::PTP::_2019::ManagementMessageBody::getActionField () const inline constexpr noexcept
Get action field value from reserved_actionField byte.
Returns
Action field value (lower 4 bits)
Definition at line 687 of file messages.hpp.
References reserved_actionField.
Referenced by validate().
setActionField()
constexpr void IEEE::_1588::PTP::_2019::ManagementMessageBody::setActionField (std::uint8_t action) inline constexpr noexcept
Set action field value in reserved_actionField byte.
Parameters
action Action field value (must be 0-15)
Definition at line 695 of file messages.hpp.
References reserved_actionField.
validate()
PTPResult< void > IEEE::_1588::PTP::_2019::ManagementMessageBody::validate () const inline noexcept
Validate management message body.
Returns
PTPResult with validation status
Definition at line 703 of file messages.hpp.
References IEEE::_1588::PTP::_2019::ManagementAction::ACKNOWLEDGE, boundaryHops, IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), getActionField(), startingBoundaryHops, and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
Member Data Documentation
boundaryHops
std::uint8_t IEEE::_1588::PTP::_2019::ManagementMessageBody::boundaryHops
Definition at line 672 of file messages.hpp.
Referenced by validate().
reserved
std::uint8_t IEEE::_1588::PTP::_2019::ManagementMessageBody::reserved
Definition at line 678 of file messages.hpp.
reserved_actionField
std::uint8_t IEEE::_1588::PTP::_2019::ManagementMessageBody::reserved_actionField
Definition at line 675 of file messages.hpp.
Referenced by getActionField(), and setActionField().
startingBoundaryHops
std::uint8_t IEEE::_1588::PTP::_2019::ManagementMessageBody::startingBoundaryHops
Definition at line 669 of file messages.hpp.
Referenced by validate().
targetPortIdentity
PortIdentity IEEE::_1588::PTP::_2019::ManagementMessageBody::targetPortIdentity
Definition at line 666 of file messages.hpp.
The documentation for this struct was generated from the following file:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/messages.hpp