IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::Types::Timestamp Struct Reference
IEEE::_1588::PTP::_2019::Types::Timestamp Struct Reference
PTP Timestamp - seconds and nanoseconds representation.
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/types.hpp>
Public Member Functions
constexpr UInteger64 getTotalSeconds () const noexcept
Get total seconds (48-bit)
constexpr void setTotalSeconds (UInteger64 total_seconds) noexcept
Set total seconds (48-bit)
constexpr bool isValid () const noexcept
Validate nanoseconds field.
PTPResult< void > validate () const noexcept
Validate timestamp fields.
constexpr bool operator< (const Timestamp &other) const noexcept
Comparison operators for Timestamp.
constexpr bool operator> (const Timestamp &other) const noexcept
constexpr bool operator<= (const Timestamp &other) const noexcept
constexpr bool operator>= (const Timestamp &other) const noexcept
constexpr bool operator== (const Timestamp &other) const noexcept
constexpr bool operator!= (const Timestamp &other) const noexcept
TimeInterval operator- (const Timestamp &other) const noexcept
Arithmetic operators for Timestamp.
Timestamp operator* (std::uint8_t multiplier) const noexcept
Multiply timestamp by scalar (for timeout calculations)
Public Attributes
UInteger48 seconds_high
Upper 16 bits of seconds (for future use)
UInteger32 seconds_low
Lower 32 bits of seconds.
UInteger32 nanoseconds
Nanoseconds (0-999,999,999)
Detailed Description
PTP Timestamp - seconds and nanoseconds representation.
Deterministic design: POD structure with deterministic operations. Hardware abstraction layer will provide time conversions.
Definition at line 154 of file types.hpp.
Member Function Documentation
getTotalSeconds()
constexpr UInteger64 IEEE::_1588::PTP::_2019::Types::Timestamp::getTotalSeconds () const inline constexpr noexcept
Get total seconds (48-bit)
Returns
Total seconds value
Note
Deterministic: O(1) execution time
Definition at line 164 of file types.hpp.
References seconds_high, and seconds_low.
Referenced by operator<(), and operator==().
isValid()
constexpr bool IEEE::_1588::PTP::_2019::Types::Timestamp::isValid () const inline constexpr noexcept
Validate nanoseconds field.
Returns
true if nanoseconds is valid (< 1,000,000,000)
Note
Deterministic: O(1) execution time
Definition at line 183 of file types.hpp.
References nanoseconds.
operator!=()
constexpr bool IEEE::_1588::PTP::_2019::Types::Timestamp::operator!= (const Timestamp & other) const inline constexpr noexcept
Definition at line 224 of file types.hpp.
operator*()
Timestamp IEEE::_1588::PTP::_2019::Types::Timestamp::operator* (std::uint8_t multiplier) const inline noexcept
Multiply timestamp by scalar (for timeout calculations)
Note
Deterministic: O(1) execution time
Definition at line 356 of file types.hpp.
References nanoseconds, and setTotalSeconds().
operator-()
TimeInterval IEEE::_1588::PTP::_2019::Types::Timestamp::operator- (const Timestamp & other) const inline noexcept
Arithmetic operators for Timestamp.
Timestamp arithmetic operator implementations.
Note
Deterministic: O(1) execution time, required for time interval calculations
Defined here after TimeInterval is complete
Definition at line 348 of file types.hpp.
operator<()
constexpr bool IEEE::_1588::PTP::_2019::Types::Timestamp::operator< (const Timestamp & other) const inline constexpr noexcept
Comparison operators for Timestamp.
Note
Deterministic: O(1) execution time, required for timeout calculations
Definition at line 198 of file types.hpp.
References getTotalSeconds(), and nanoseconds.
operator<=()
constexpr bool IEEE::_1588::PTP::_2019::Types::Timestamp::operator<= (const Timestamp & other) const inline constexpr noexcept
Definition at line 211 of file types.hpp.
operator==()
constexpr bool IEEE::_1588::PTP::_2019::Types::Timestamp::operator== (const Timestamp & other) const inline constexpr noexcept
Definition at line 219 of file types.hpp.
References getTotalSeconds(), and nanoseconds.
operator>()
constexpr bool IEEE::_1588::PTP::_2019::Types::Timestamp::operator> (const Timestamp & other) const inline constexpr noexcept
Definition at line 207 of file types.hpp.
operator>=()
constexpr bool IEEE::_1588::PTP::_2019::Types::Timestamp::operator>= (const Timestamp & other) const inline constexpr noexcept
Definition at line 215 of file types.hpp.
setTotalSeconds()
constexpr void IEEE::_1588::PTP::_2019::Types::Timestamp::setTotalSeconds (UInteger64 total_seconds) inline constexpr noexcept
Set total seconds (48-bit)
Parameters
total_seconds Total seconds value
Note
Deterministic: O(1) execution time
Definition at line 173 of file types.hpp.
References seconds_high, and seconds_low.
Referenced by operator*().
validate()
PTPResult< void > IEEE::_1588::PTP::_2019::Types::Timestamp::validate () const inline noexcept
Validate timestamp fields.
Returns
PTPResult indicating success or error
Note
Required for message validation compatibility
Definition at line 809 of file types.hpp.
References IEEE::_1588::PTP::_2019::Types::Invalid_Timestamp, IEEE::_1588::PTP::_2019::Types::PTPResult< T >::makeError(), and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
Referenced by IEEE::_1588::PTP::_2019::SyncBody::validate(), IEEE::_1588::PTP::_2019::FollowUpBody::validate(), IEEE::_1588::PTP::_2019::DelayRespBody::validate(), IEEE::_1588::PTP::_2019::PdelayRespBody::validate(), and IEEE::_1588::PTP::_2019::PdelayRespFollowUpBody::validate().
Member Data Documentation
nanoseconds
UInteger32 IEEE::_1588::PTP::_2019::Types::Timestamp::nanoseconds
Nanoseconds (0-999,999,999)
Definition at line 157 of file types.hpp.
Referenced by isValid(), operator*(), operator<(), and operator==().
seconds_high
UInteger48 IEEE::_1588::PTP::_2019::Types::Timestamp::seconds_high
Upper 16 bits of seconds (for future use)
Definition at line 155 of file types.hpp.
Referenced by getTotalSeconds(), and setTotalSeconds().
seconds_low
UInteger32 IEEE::_1588::PTP::_2019::Types::Timestamp::seconds_low
Lower 32 bits of seconds.
Definition at line 156 of file types.hpp.
Referenced by getTotalSeconds(), and setTotalSeconds().
The documentation for this struct was generated from the following file:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/types.hpp