IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::Clocks::BoundaryClock Class Reference
IEEE::_1588::PTP::_2019::Clocks::BoundaryClock Class Reference
Boundary Clock State Machine.
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/clocks.hpp>
Public Member Functions
BoundaryClock (const std::array< PortConfiguration, MAX_PORTS > &port_configs, std::size_t port_count, const StateCallbacks &callbacks) noexcept
Construct Boundary Clock.
BoundaryClock (const BoundaryClock &)=delete
Non-copyable for deterministic resource management.
BoundaryClock & operator= (const BoundaryClock &)=delete
BoundaryClock (BoundaryClock &&) noexcept=default
Movable for efficient initialization.
BoundaryClock & operator= (BoundaryClock &&) noexcept=default
~BoundaryClock () noexcept=default
Destructor ensures clean resource release.
Types::PTPResult< void > initialize () noexcept
Initialize boundary clock.
Types::PTPResult< void > start () noexcept
Start clock operation.
Types::PTPResult< void > stop () noexcept
Stop clock operation.
Types::PTPResult< void > process_message (Types::PortNumber port_number, std::uint8_t message_type, const void *message_data, std::size_t message_size, const Types::Timestamp &rx_timestamp) noexcept
Process received PTP message on specific port.
Types::PTPResult< void > tick (const Types::Timestamp &current_time) noexcept
Execute periodic clock tasks.
constexpr std::size_t get_port_count () const noexcept
Get number of active ports.
const PtpPort * get_port (Types::PortNumber port_number) const noexcept
Get specific port by number.
constexpr ClockType get_clock_type () const noexcept
Get clock type.
bool has_master_port () const noexcept
Check if any port is master.
bool has_slave_port () const noexcept
Check if any port is slave.
bool is_synchronized () const noexcept
Check if clock is synchronized (has synchronized slave port)
Static Public Attributes
static constexpr std::size_t MAX_PORTS = 8
Maximum ports for deterministic arrays.
Detailed Description
Boundary Clock State Machine.
IEEE 1588-2019 Boundary Clock implementation with multiple ports and deterministic state coordination per Section 6.5.3.
Definition at line 936 of file clocks.hpp.
Constructor & Destructor Documentation
BoundaryClock() [1/3]
IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::BoundaryClock (const std::array< PortConfiguration, MAX_PORTS > & port_configs, std::size_t port_count, const StateCallbacks & callbacks) explicit noexcept
Construct Boundary Clock.
Parameters
port_configs Array of port configurations
port_count Number of active ports
callbacks Hardware abstraction callbacks
Definition at line 1406 of file clocks.cpp.
BoundaryClock() [2/3]
IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::BoundaryClock (const BoundaryClock &) delete
Non-copyable for deterministic resource management.
BoundaryClock() [3/3]
IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::BoundaryClock (BoundaryClock &&) default noexcept
Movable for efficient initialization.
~BoundaryClock()
IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::~BoundaryClock () default noexcept
Destructor ensures clean resource release.
Member Function Documentation
get_clock_type()
constexpr ClockType IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::get_clock_type () const inline constexpr noexcept
Get clock type.
Definition at line 1016 of file clocks.hpp.
get_port()
const PtpPort * IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::get_port (Types::PortNumber port_number) const noexcept
Get specific port by number.
Definition at line 1518 of file clocks.cpp.
get_port_count()
constexpr std::size_t IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::get_port_count () const inline constexpr noexcept
Get number of active ports.
Definition at line 1010 of file clocks.hpp.
has_master_port()
bool IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::has_master_port () const noexcept
Check if any port is master.
Definition at line 1522 of file clocks.cpp.
has_slave_port()
bool IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::has_slave_port () const noexcept
Check if any port is slave.
Definition at line 1531 of file clocks.cpp.
initialize()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::initialize () noexcept
Initialize boundary clock.
Returns
Success/failure result
Definition at line 1417 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
is_synchronized()
bool IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::is_synchronized () const noexcept
Check if clock is synchronized (has synchronized slave port)
Definition at line 1540 of file clocks.cpp.
References is_synchronized().
Referenced by is_synchronized().
operator=() [1/2]
BoundaryClock & IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::operator= (BoundaryClock &&) default noexcept
operator=() [2/2]
BoundaryClock & IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::operator= (const BoundaryClock &) delete
process_message()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::process_message (Types::PortNumber port_number, std::uint8_t message_type, const void * message_data, std::size_t message_size, const Types::Timestamp & rx_timestamp) noexcept
Process received PTP message on specific port.
Parameters
port_number Port that received the message
message_type Type of PTP message
message_data Message data buffer
message_size Size of message data
rx_timestamp Hardware receive timestamp
Returns
Success/failure result
Definition at line 1450 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), IEEE::_1588::PTP::_2019::Types::INVALID_MESSAGE_SIZE, IEEE::_1588::PTP::_2019::Types::INVALID_PORT, IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_announce(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_delay_req(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_delay_resp(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_follow_up(), IEEE::_1588::PTP::_2019::Clocks::PtpPort::process_sync(), IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success(), and IEEE::_1588::PTP::_2019::Types::UNSUPPORTED_MESSAGE.
start()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::start () noexcept
Start clock operation.
Returns
Success/failure result
Definition at line 1428 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
stop()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::stop () noexcept
Stop clock operation.
Returns
Success/failure result
Definition at line 1439 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
tick()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::tick (const Types::Timestamp & current_time) noexcept
Execute periodic clock tasks.
Parameters
current_time Current system time
Returns
Success/failure result
Definition at line 1507 of file clocks.cpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
Member Data Documentation
MAX_PORTS
constexpr std::size_t IEEE::_1588::PTP::_2019::Clocks::BoundaryClock::MAX_PORTS = 8 static constexpr
Maximum ports for deterministic arrays.
Definition at line 938 of file clocks.hpp.
The documentation for this class was generated from the following files:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/clocks.hpp
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/src/clocks.cpp