IEEE 1588-2019 PTP Library: Common::utils::fi::detail Namespace Reference
Common::utils::fi::detail Namespace Reference
Functions
std::atomic< bool > & offset_jitter_enabled () noexcept
std::atomic< long long > & offset_jitter_ns () noexcept
std::atomic< int > & bmca_tie_tokens () noexcept
std::atomic< bool > & bmca_tie_forced_observed () noexcept
Function Documentation
bmca_tie_forced_observed()
std::atomic< bool > & Common::utils::fi::detail::bmca_tie_forced_observed () inline noexcept
Definition at line 35 of file fault_injection.hpp.
Referenced by Common::utils::fi::mark_bmca_tie_forced_observed(), Common::utils::fi::reset(), and Common::utils::fi::was_bmca_tie_forced_and_clear().
bmca_tie_tokens()
std::atomic< int > & Common::utils::fi::detail::bmca_tie_tokens () inline noexcept
Definition at line 30 of file fault_injection.hpp.
Referenced by Common::utils::fi::consume_bmca_tie_token(), Common::utils::fi::force_bmca_tie_next(), and Common::utils::fi::reset().
offset_jitter_enabled()
std::atomic< bool > & Common::utils::fi::detail::offset_jitter_enabled () inline noexcept
Definition at line 21 of file fault_injection.hpp.
Referenced by Common::utils::fi::enable_offset_jitter(), Common::utils::fi::is_offset_jitter_enabled(), and Common::utils::fi::reset().
offset_jitter_ns()
std::atomic< long long > & Common::utils::fi::detail::offset_jitter_ns () inline noexcept
Definition at line 25 of file fault_injection.hpp.
Referenced by Common::utils::fi::get_offset_jitter_ns(), Common::utils::fi::reset(), and Common::utils::fi::set_offset_jitter_ns().