IEEE 1588-2019 PTP Library: Common::utils::metrics::detail Namespace Reference
Common::utils::metrics::detail Namespace Reference
Functions
std::array< std::atomic< std::uint64_t >, static_cast< std::size_t >(CounterId::COUNT)> & counters () noexcept
Function Documentation
counters()
std::array< std::atomic< std::uint64_t >, static_cast< std::size_t >(CounterId::COUNT)> & Common::utils::metrics::detail::counters () inline noexcept
Definition at line 47 of file metrics.hpp.
References Common::utils::metrics::COUNT.
Referenced by Common::utils::metrics::get(), Common::utils::metrics::increment(), Common::utils::metrics::reset(), and Common::utils::metrics::snapshot().