IEEE 1588-2019 PTP Library: Common::utils::health Namespace Reference
Common::utils::health Namespace Reference
Namespaces
namespace detail
Classes
struct SelfTestReport
Typedefs
using health_observer_t = void(*)(const SelfTestReport &)
Functions
void record_bmca_selection (int index) noexcept
void record_offset_ns (long long ns) noexcept
void record_bmca_forced_tie (bool forced) noexcept
SelfTestReport self_test () noexcept
void set_observer (health_observer_t cb) noexcept
void emit () noexcept
Typedef Documentation
health_observer_t
using Common::utils::health::health_observer_t = typedef void(*)(const SelfTestReport&)
Definition at line 94 of file health.hpp.
Function Documentation
emit()
void Common::utils::health::emit () inline noexcept
Definition at line 107 of file health.hpp.
References Common::utils::health::detail::observer(), and self_test().
Referenced by IEEE::_1588::PTP::_2019::Clocks::SynchronizationData::calculateOffset(), and IEEE::_1588::PTP::_2019::Clocks::PtpPort::tick().
record_bmca_forced_tie()
void Common::utils::health::record_bmca_forced_tie (bool forced) inline noexcept
Definition at line 67 of file health.hpp.
References Common::utils::health::detail::bmca_tie_forced().
record_bmca_selection()
void Common::utils::health::record_bmca_selection (int index) inline noexcept
Definition at line 59 of file health.hpp.
References Common::utils::health::detail::last_bmca_index().
record_offset_ns()
void Common::utils::health::record_offset_ns (long long ns) inline noexcept
Definition at line 63 of file health.hpp.
References Common::utils::health::detail::last_offset_ns().
Referenced by IEEE::_1588::PTP::_2019::Clocks::SynchronizationData::calculateOffset().
self_test()
SelfTestReport Common::utils::health::self_test () inline noexcept
Definition at line 72 of file health.hpp.
References Common::utils::health::detail::bmca_tie_forced(), Common::utils::fi::is_offset_jitter_enabled(), Common::utils::health::detail::last_bmca_index(), Common::utils::health::detail::last_offset_ns(), Common::utils::health::SelfTestReport::offsetsComputed, and Common::utils::metrics::snapshot().
Referenced by emit().
set_observer()
void Common::utils::health::set_observer (health_observer_t cb) inline noexcept
Definition at line 103 of file health.hpp.
References Common::utils::health::detail::observer().