IEEE 1588-2019 PTP Library: IEEE::_1588::PTP::_2019::Integration::BMCAIntegration Class Reference
IEEE::_1588::PTP::_2019::Integration::BMCAIntegration Class Reference
BMCA Integration Coordinator.
#include </home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/bmca_integration.hpp>
Classes
struct Configuration
Configuration for BMCA execution behavior.
Public Member Functions
BMCAIntegration (Clocks::PtpPort &port) noexcept
Construct BMCA coordinator with port reference.
Types::PTPResult< void > configure (const Configuration &config) noexcept
Configure BMCA execution behavior.
Types::PTPResult< void > start () noexcept
Start BMCA execution coordination.
Types::PTPResult< void > stop () noexcept
Stop BMCA execution coordination.
Types::PTPResult< void > tick (const Types::Timestamp &current_time) noexcept
Periodic tick for BMCA execution and health monitoring.
Types::PTPResult< void > execute_bmca (const Types::Timestamp &current_time) noexcept
Force immediate BMCA execution.
const BMCAStatistics & get_statistics () const noexcept
Get current BMCA statistics.
BMCAHealthStatus get_health_status () const noexcept
Get current health status.
void reset () noexcept
Reset all statistics and health indicators.
bool is_running () const noexcept
Check if coordinator is running.
Detailed Description
BMCA Integration Coordinator.
Manages BMCA execution lifecycle, decision propagation, and monitoring. Integrates with PtpPort for protocol operations and provides observability through metrics and health reporting.
Usage:
BMCAIntegration bmca_coordinator(port);
bmca_coordinator.configure(config);
bmca_coordinator.start();
// In main loop
bmca_coordinator.tick(current_time);
// Query health
auto health = bmca_coordinator.get_health_status();
auto stats = bmca_coordinator.get_statistics();
Definition at line 117 of file bmca_integration.hpp.
Constructor & Destructor Documentation
BMCAIntegration()
IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::BMCAIntegration (Clocks::PtpPort & port) inline explicit noexcept
Construct BMCA coordinator with port reference.
Parameters
port PTP port to coordinate BMCA for
Definition at line 142 of file bmca_integration.hpp.
Member Function Documentation
configure()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::configure (const Configuration & config) inline noexcept
Configure BMCA execution behavior.
Parameters
config Configuration parameters
Returns
Success if configuration valid
Definition at line 159 of file bmca_integration.hpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), IEEE::_1588::PTP::_2019::Types::Invalid_Parameter, and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
execute_bmca()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::execute_bmca (const Types::Timestamp & current_time) noexcept
Force immediate BMCA execution.
Useful when Announce message received or configuration changed.
Parameters
current_time Current timestamp
Returns
Success if BMCA executed successfully
Definition at line 62 of file bmca_integration.cpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), and IEEE::_1588::PTP::_2019::Types::State_Error.
get_health_status()
BMCAHealthStatus IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::get_health_status () const inline noexcept
Get current health status.
Returns
Current health indicators
Definition at line 242 of file bmca_integration.hpp.
get_statistics()
const BMCAStatistics & IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::get_statistics () const inline noexcept
Get current BMCA statistics.
Returns
Reference to current statistics
Definition at line 233 of file bmca_integration.hpp.
is_running()
bool IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::is_running () const inline noexcept
Check if coordinator is running.
Returns
true if started and operational
Definition at line 259 of file bmca_integration.hpp.
Referenced by IEEE::_1588::PTP::_2019::MessageFlowCoordinator::get_health_status().
reset()
void IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::reset () inline noexcept
Reset all statistics and health indicators.
Definition at line 249 of file bmca_integration.hpp.
References IEEE::_1588::PTP::_2019::Integration::BMCAStatistics::reset().
start()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::start () inline noexcept
Start BMCA execution coordination.
Resets statistics and enables periodic execution.
Returns
Success if started successfully
Definition at line 178 of file bmca_integration.hpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), IEEE::_1588::PTP::_2019::Integration::BMCAStatistics::reset(), IEEE::_1588::PTP::_2019::Types::State_Error, and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
Referenced by IEEE::_1588::PTP::_2019::MessageFlowCoordinator::start().
stop()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::stop () inline noexcept
Stop BMCA execution coordination.
Disables periodic execution but preserves statistics.
Returns
Success if stopped successfully
Definition at line 198 of file bmca_integration.hpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), IEEE::_1588::PTP::_2019::Types::State_Error, and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
Referenced by IEEE::_1588::PTP::_2019::MessageFlowCoordinator::start().
tick()
Types::PTPResult< void > IEEE::_1588::PTP::_2019::Integration::BMCAIntegration::tick (const Types::Timestamp & current_time) noexcept
Periodic tick for BMCA execution and health monitoring.
Executes BMCA if interval expired and config permits. Updates health status and metrics.
Parameters
current_time Current timestamp
Returns
Success if tick processed successfully
Definition at line 24 of file bmca_integration.cpp.
References IEEE::_1588::PTP::_2019::Types::PTPResult< T >::failure(), IEEE::_1588::PTP::_2019::Types::State_Error, and IEEE::_1588::PTP::_2019::Types::PTPResult< T >::success().
The documentation for this class was generated from the following files:
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/include/IEEE/1588/PTP/2019/bmca_integration.hpp
/home/runner/work/IEEE_1588_2019/IEEE_1588_2019/src/bmca_integration.cpp